// Defines for Altap Translator
#define IDOK                1
#define IDCANCEL            2
#define IDABORT             3
#define IDRETRY             4
#define IDIGNORE            5
#define IDYES               6
#define IDNO                7
#define IDCLOSE             8
#define IDHELP              9

///* X:\ALTAP\PETR\salamand\plugins\wmobile\lang\lang.rh
//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by lang.rc
//
#define IDD_PROGRESSDLG                 500
#define IDT_OPERATION                   501
#define IDT_FILENAME                    502
#define IDP_PROGRESSBAR                 503
#define IDD_PROGRESS2DLG                510
#define IDT_OPERATION2                  511
#define IDT_FILENAME2                   512
#define IDP_PROGRESSBAR2                513
#define IDD_ATTRIBUTES                  520
#define IDC_ARCHIVE                     521
#define IDC_HIDDEN                      522
#define IDC_READONLY                    523
#define IDC_SYSTEM                      524
#define IDC_ATTR_MODIFIED_DATE          526
#define IDC_ATTR_MODIFIED_TIME          527
#define IDC_ATTR_CREATED_DATE           528
#define IDC_ATTR_CREATED_TIME           529
#define IDC_ATTR_ACCESSED_DATE          530
#define IDC_ATTR_ACCESSED_TIME          531
#define IDC_ATTR_CURRENT                532
#define IDC_RECURSESUBDIRS              533

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        8500
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         8700
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
///* X:\ALTAP\PETR\salamand\plugins\wmobile\wmobile.rh2
#pragma once

#if defined(APSTUDIO_INVOKED) && !defined(APSTUDIO_READONLY_SYMBOLS)
#error this file is not editable by Microsoft Visual C++
#endif //defined(APSTUDIO_INVOKED) && !defined(APSTUDIO_READONLY_SYMBOLS)

#define IDC_STATIC_1 900
#include "statics.rh2"   // 900 az 939 jsou timto zabrane !!!

#define IDI_FS            1002

#define IDS_PLUGINNAME          2000
#define IDS_PLUGIN_DESCRIPTION  2001
#define IDS_ABOUT               2002


#define IDS_WMPLUGINTITLE           3000
#define IDS_WMPLUGINTITLE_ERROR     3001
#define IDS_WMPLUGINTITLE_QUESTION  3002

#define IDS_ERR_CONNECTION          3003
#define IDS_CONNECTING              3004
#define IDS_PATH_ERROR              3005
#define IDS_YESNO_CANCEL            3006
#define IDS_ERR_MEMORYLOW           3007
#define IDS_ERR_PATHTOOLONG         3008
#define IDS_ERR_CREATEDIR           3009
#define IDS_YESNO_CREATEDIR         3010
#define IDS_ERR_DIRNAMEISFILE       3011
#define IDS_ERR_INVALIDDATEFORMAT   3012
#define IDS_ERR_NAMETOOLONG         3013
#define IDS_ERR_FILEINPATH          3014
#define IDS_YESNO_CONNETCLOSEPLUGIN 3015
#define IDS_SORRY_CREATEDIR1        3016
#define IDS_SORRY_CREATEDIR2        3017
#define IDS_SORRY_CREATEDIR3        3018
#define IDS_ERR_INVALIDPATH         3019
#define IDS_READ                    3020
#define IDS_READING                 3021
#define IDS_WAIT_READINGDIRTREE     3022
#define IDS_DELETE                  3023
#define IDS_DELETING                3024
#define IDS_YESNO_DELETENOEMPTYDIR  3025
#define IDS_YESNO_DELETEHIDDENFILE  3026
#define IDS_YESNO_DELETEHIDDENDIR   3027
#define IDS_ERR_TARGETPATHNOEXISTS  3028
#define IDS_ERR_COPYTOOTHERFS       3029
#define IDS_ERR_COPYTOARCHIVES      3030
#define IDS_COPY                    3031
#define IDS_COPYING                 3032
#define IDS_MOVE                    3033
#define IDS_MOVING                  3034
#define IDS_TO                      3035
#define IDS_ERR_COPYDIRTOITSELF     3036
#define IDS_ERR_COPYFILETOITSELF    3037
#define IDS_YESNO_OVERWRITEHIDDENFILE 3038
#define IDS_ERR_MOVEDIRTOITSELF     3039
#define IDS_ERR_MOVEFILETOITSELF    3040
#define IDS_ATTRIBUTES              3041
#define IDS_CHANGING                3042
///* X:\ALTAP\PETR\salamand\plugins\shared\statics.rh2
//#define IDC_STATIC_1        (IDC_STATIC_1+0) // definovano v nadrazenem headru
#define IDC_STATIC_2        (IDC_STATIC_1+1)
#define IDC_STATIC_3        (IDC_STATIC_1+2)
#define IDC_STATIC_4        (IDC_STATIC_1+3)
#define IDC_STATIC_5        (IDC_STATIC_1+4)
#define IDC_STATIC_6        (IDC_STATIC_1+5)
#define IDC_STATIC_7        (IDC_STATIC_1+6)
#define IDC_STATIC_8        (IDC_STATIC_1+7)
#define IDC_STATIC_9        (IDC_STATIC_1+8)
#define IDC_STATIC_10       (IDC_STATIC_1+9)
#define IDC_STATIC_11       (IDC_STATIC_1+10)
#define IDC_STATIC_12       (IDC_STATIC_1+11)
#define IDC_STATIC_13       (IDC_STATIC_1+12)
#define IDC_STATIC_14       (IDC_STATIC_1+13)
#define IDC_STATIC_15       (IDC_STATIC_1+14)
#define IDC_STATIC_16       (IDC_STATIC_1+15)
#define IDC_STATIC_17       (IDC_STATIC_1+16)
#define IDC_STATIC_18       (IDC_STATIC_1+17)
#define IDC_STATIC_19       (IDC_STATIC_1+18)
#define IDC_STATIC_20       (IDC_STATIC_1+19)
#define IDC_STATIC_21       (IDC_STATIC_1+20)
#define IDC_STATIC_22       (IDC_STATIC_1+21)
#define IDC_STATIC_23       (IDC_STATIC_1+22)
#define IDC_STATIC_24       (IDC_STATIC_1+23)
#define IDC_STATIC_25       (IDC_STATIC_1+24)
#define IDC_STATIC_26       (IDC_STATIC_1+25)
#define IDC_STATIC_27       (IDC_STATIC_1+26)
#define IDC_STATIC_28       (IDC_STATIC_1+27)
#define IDC_STATIC_29       (IDC_STATIC_1+28)
#define IDC_STATIC_30       (IDC_STATIC_1+29)
#define IDC_STATIC_31       (IDC_STATIC_1+30)
#define IDC_STATIC_32       (IDC_STATIC_1+31)
#define IDC_STATIC_33       (IDC_STATIC_1+32)
#define IDC_STATIC_34       (IDC_STATIC_1+33)
#define IDC_STATIC_35       (IDC_STATIC_1+34)
#define IDC_STATIC_36       (IDC_STATIC_1+35)
#define IDC_STATIC_37       (IDC_STATIC_1+36)
#define IDC_STATIC_38       (IDC_STATIC_1+37)
#define IDC_STATIC_39       (IDC_STATIC_1+38)
#define IDC_STATIC_40       (IDC_STATIC_1+39)
