// SPDX-FileCopyrightText: 2023 Open Salamander Authors
// SPDX-License-Identifier: GPL-2.0-or-later

/****************************************************************************


resource.h

produced by Borland Resource Workshop


*****************************************************************************/

//dialogs
#define IDD_PASSWORD 125
#define IDCURSOR_HAND 300
//#define IDD_SFXDIALOG 100
#define IDC_ANIMATION 104
#define IDC_FILE 103
#define IDC_PROGRESS 105
#define IDC_SEPARATOR 124
#define IDC_ABOUTTEXT 123
#define IDC_ABOUT 122
#define IDC_TEXT 121
#define IDC_TARGETPATH 120
#define IDC_WEBLINK 119
#define IDC_BROWSE 102
#define IDC_PATH 101
#define IDD_OVERWRITE 106
#define IDC_SOURCENAME 107
#define IDC_SOURCEATTR 108
#define IDC_TARGETNAME 109
#define IDC_TARGETATTR 110
#define IDC_ALL 111
#define IDC_SKIP 112
#define IDC_SKIPALL 113
#define IDC_PASSWORD 126
#define IDC_WITHFILE 118
#define IDC_RETRY 114
#define IDD_ERROR 115
#define IDC_FILENAME 116
#define IDC_ERROR 117
#define IDC_VENDOR 127

#define IDD_LONGMESSAGE 120
#define IDE_MESSAGE 121
