// Defines for Altap Translator
#define IDOK                1
#define IDCANCEL            2
#define IDABORT             3
#define IDRETRY             4
#define IDIGNORE            5
#define IDYES               6
#define IDNO                7
#define IDCLOSE             8
#define IDHELP              9

///* X:\ALTAP\PETR\salamand\plugins\automation\lang\lang.rh
//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by lang.rc
//
#define IDS_PLUGINNAME                  1
#define IDS_DESCRIPTION                 2
#define IDS_ABOUT                       3
#define IDD_INPUTBOX                    100
#define IDC_INPUTBOX                    101
#define IDD_CONFIG                      101
#define IDM_BROWSE                      106
#define IDS_SCRIPTERROR                 128
#define IDS_LINE                        129
#define IDS_COLUMN                      130
#define IDS_ERROR                       131
#define IDS_RUNFOCUSED                  132
#define IDS_PROGRESSTITLE               134
#define IDS_SOURCE                      135
#define IDS_SCRIPTPOPUPMENU             136
#define IDS_MENUEMPTY                   137
#define IDS_LOADERRFMT                  138
#define IDS_UNKERROR                    139
#define IDS_ABORT                       140
#define IDS_DEBUGABORT                  141
#define IDS_ADDDIRTITLE                 142
#define IDS_ADDDIRDESCR                 143
#define IDS_ABORTCAPTION                144
#define IDS_ABORTTIP                    145
#define IDS_MAINWINDOWLOCKED            146
#define IDS_ENGINECREATEFAIL            147
#define IDS_E_INVALIDARCHIVE            256
#define IDS_E_CANNOTCLOSEPATH           257
#define IDS_E_SHORTERPATH               258
#define IDS_E_READONLYWHILEPROGRESSSHOWN 259
#define IDS_E_READONLYWHILEPROGRESSHIDDEN 260
#define IDS_E_PLUGLOADFAIL              261
#define IDS_E_PLUGERROR                 262
#define IDS_E_CACHEERROR                263
#define IDS_E_FILEMASKSYNTAX            264
#define IDS_E_NOTCOMPONENT              265
#define IDS_E_FORMPUT                   266
#define IDS_E_SCRIPTABORTED             267
#define IDC_DIRLIST                     371
#define IDC_DIRLISTHEADER               375
#define IDC_ENABLEDBG                   1001
#define IDC_STATIC_1                    1003
#define IDC_PROMPT                      1150
#define ID__BROWSE                      40010
#define ID__SALAMANDERDIRECTORY         40011
#define ID__ENVIRONMENTVARIABLE         40012
#define ID_BROWSE                       40013
#define ID_SALDIR                       40014
#define ID_ENVVAR                       40015

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40016
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
///* X:\ALTAP\PETR\salamand\plugins\automation\automation.rh2
//	Automation Plugin for Altap Salamander
//	
//	Copyright (c) 2009-2016 Milan Kase <manison@manison.cz>
//	Copyright (c) 2010-2016 ALTAP, spol. s r.o.
//	
//	automation.rh2
//	Resources Microsoft Visual C++ does not edit directly.

#pragma once

#if defined(APSTUDIO_INVOKED) && !defined(APSTUDIO_READONLY_SYMBOLS)
#error this file is not editable by Microsoft Visual C++
#endif //defined(APSTUDIO_INVOKED) && !defined(APSTUDIO_READONLY_SYMBOLS)

#define IDI_MAIN                        1
#define IDB_ICONSTRIP                   128
