// Defines for Altap Translator
#define IDOK                1
#define IDCANCEL            2
#define IDABORT             3
#define IDRETRY             4
#define IDIGNORE            5
#define IDYES               6
#define IDNO                7
#define IDCLOSE             8
#define IDHELP              9

///* X:\ALTAP\PETR\salamand\plugins\pictview\lang\lang.rh
//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by lang.rc
//
#define DLG_ABOUT                       2000
#define IDC_ABOUT_FRAME                 2001
#define IDC_ABOUT_L1                    2002
#define IDC_ABOUT_L2                    2004
#define IDC_ABOUT_L3                    2005
#define IDC_ABOUT_L4                    2006
#define IDC_ABOUT_TITLE                 2007
#define IDC_ABOUT_PVW32                 2008
#define IDC_ABOUT_EMAIL                 2009
#define IDC_ABOUT_WWW                   2010
#define IDC_ABOUT_COPYRIGHT             2011
#define IDC_ABOUT_ICON                  2013
#define DLG_CFGPAGE_APPEARANCE          2020
#define IDC_CFGAPP_WINPOS_SAME          2021
#define IDC_CFGAPP_WINPOS_LARGER        2022
#define IDC_CFGAPP_WINPOS_ANY           2023
#define IDC_CFGAPP_ZOOM_WHOLE           2024
#define IDC_CFGAPP_ZOOM_WIDTH           2025
#define IDC_CFGAPP_ZOOM_ORIG            2026
#define IDC_CFGAPP_ZOOM_FSCREEN         2027
#define IDC_CFGAPP_PATH                 2030
#define DLG_CFGPAGE_ADVANCED            2040
#define IDC_CFGADV_CREATE_THUMBNAILS    2050
#define IDC_CFGADV_THUMB_MP             2051
#define IDC_CFGADV_AUTOROTATE           2052
#define IDC_CFGADV_SAVE                 2053
#define IDC_CFGADV_REMEMBER_PATH        2054
#define DLG_CFGPAGE_KEYBOARD            2060
#define IDC_CFGKBD_PGDNUP_SCR           2061
#define IDC_CFGKBD_PGDNUP_PREV          2062
#define DLG_CFGPAGE_TOOLS               2070
#define IDC_CFGTOOLS_SQUARE             2071
#define IDC_CFGTOOLS_4_3                2072
#define IDC_CFGTOOLS_3_2                2073
#define IDC_CFGTOOLS_16_9               2074
#define IDC_CFGTOOLS_OTHER              2075
#define IDC_CFGTOOLS_RATIO_X            2076
#define IDC_CFGTOOLS_RATIO_Y            2077
#define IDC_CFGTOOLS_PIPHEX             2078
#define DLG_CFGPAGE_COLORS              2080
#define IDC_CFGCLR_BKGND                2081
#define IDC_CFGCLR_BORDER               2082
#define IDC_CFGCLR_FS_BKGND             2083
#define IDC_CFGCLR_FS_BORDER            2084
#define DLG_IMGPROP                     2100
#define IDC_IMGPROP_FNAME               2101
#define IDC_IMGPROP_PAGENUM_LBL         2102
#define IDC_IMGPROP_PAGENUM             2103
#define IDC_IMGPROP_WIDTH               2104
#define IDC_IMGPROP_HEIGHT              2105
#define IDC_IMGPROP_COLORS              2106
#define IDC_IMGPROP_SIZE                2107
#define IDC_IMGPROP_FSIZE               2108
#define IDC_IMGPROP_DPI                 2109
#define IDC_IMGPROP_FMT                 2110
#define IDC_IMGPROP_COMPR               2111
#define IDC_IMGPROP_COMMENT             2112
#define DLG_IMGEXIF                     2120
#define IDC_IMGEXIF_LIST                2121
#define IDC_IMGEXIF_COPY                2122
#define IDC_IMGEXIF_HIGHLIGHT           2123
#define IDC_IMGEXIF_INFO                2124
#define IDC_IMGEXIF_GROUP               2125
#define DLG_ZOOM                        2130
#define IDC_ZOOM_ZOOM                   2131
#define DLG_PAGE                        2140
#define IDC_PAGE_PAGE                   2141
#define DLG_CAPTURE                     2150
#define IDC_CAPTURE_TIMER_VAL           2151
#define IDC_CAPTURE_CURSOR              2152
#define IDC_CAPTURE_TIMER               2153
#define IDC_CAPTURE_HOTKEY_VAL          2154
#define IDC_CAPTURE_HOTKEY              2155
#define IDC_CAPTURE_CLIENT              2156
#define IDC_CAPTURE_WINDOW              2157
#define IDC_CAPTURE_FULL                2158
#define IDC_CAPTURE_VIRTUAL             2159
#define IDC_CAPTURE_APPL                2160
#define IDD_RENAMEDIALOG                2170
#define IDS_SUBJECT                     2171
#define IDE_PATH                        2172
#define IDD_OVERWRITE                   2180
#define IDS_SOURCENAME                  2181
#define IDS_SOURCEATTR                  2182
#define IDS_TARGETNAME                  2183
#define IDS_TARGETATTR                  2184
#define IDD_COPYTO                      2400
#define IDC_COPYTO_RB_1                 2401
#define IDC_COPYTO_RB_2                 2402
#define IDC_COPYTO_RB_3                 2403
#define IDC_COPYTO_RB_4                 2404
#define IDC_COPYTO_RB_5                 2405
#define IDC_COPYTO_EL_1                 2406
#define IDC_COPYTO_EL_2                 2407
#define IDC_COPYTO_EL_3                 2408
#define IDC_COPYTO_EL_4                 2409
#define IDC_COPYTO_EL_5                 2410
#define IDC_COPYTO_BR_1                 2411
#define IDC_COPYTO_BR_2                 2412
#define IDC_COPYTO_BR_3                 2413
#define IDC_COPYTO_BR_4                 2414
#define IDC_COPYTO_BR_5                 2415
#define IDD_PRINT                       2500
#define IDC_PRINT_TOP                   2501
#define IDC_PRINT_TOP_UNITS             2502
#define IDC_PRINT_LEFT                  2503
#define IDC_PRINT_LEFT_UNITS            2504
#define IDC_PRINT_SCALE                 2505
#define IDC_PRINT_FIT                   2506
#define IDC_PRINT_ASPECT                2507
#define IDC_PRINT_HEIGHT                2508
#define IDC_PRINT_HEIGHT_UNITS          2509
#define IDC_PRINT_WIDTH                 2510
#define IDC_PRINT_WIDTH_UNITS           2511
#define IDC_PRINT_BOX                   2512
#define IDC_PRINT_SELECTION             2513
#define IDC_PRINT_PRINTER               2514
#define IDC_PRINT_SETUP                 2515
#define IDC_PRINT_CENTER                2516
#define IDC_PRINT_PREVIEW               2517
#define DLG_WIAPROGRESS                 2530
#define IDC_WIAPROGR_MESSAGE            2531
#define IDC_WIAPROGR_BAR                2532

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        8500
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         8700
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
///* X:\ALTAP\PETR\salamand\plugins\pictview\pictview.rh2
#pragma once

#if defined(APSTUDIO_INVOKED) && !defined(APSTUDIO_READONLY_SYMBOLS)
#error this file is not editable by Microsoft Visual C++
#endif //defined(APSTUDIO_INVOKED) && !defined(APSTUDIO_READONLY_SYMBOLS)

#define IDC_STATIC_1 3000
#include "statics.rh2"   // 3000 az 3039 jsou timto zabrane !!!

// ikona pro hlavni okno
#define IDI_WINDOW_ICON       70
#define IDI_SB_ANCHOR         71
#define IDI_SB_CURSOR         72
#define IDI_SB_PIPETTE        73
#define IDI_SB_SIZE           74

// kruzory: normalni a sevrena ruka
#define IDC_HAND1             80
#define IDC_HAND2             81
#define IDC_PIPETA            82
#define IDC_ZOOMIN            83
#define IDC_ZOOMOUT           84
#define IDC_SELECT            85

#define IDA_ACCELERATORS      90

// nastrojove listy
#define IDB_TOOLBAR16         95
#define IDB_TOOLBAR256        96
#define IDB_PICTVIEW          97

//
// Commands
//

#define IDM_CTX_MENU          100
#define CMD_ZOOM_TO           101
#define CMD_ZOOM_IN           102
#define CMD_ZOOM_OUT          103
#define CMD_COPY              104
#define CMD_PASTE             105
#define CMD_ABOUT             106
#define CMD_CFG               112
#define CMD_RELOAD            113
#define CMD_IMG_PROP          114
#define CMD_IMG_EXIF          115
#define CMD_MIRROR_HOR        120
#define CMD_MIRROR_VERT       121
#define CMD_OPEN              122
#define CMD_SAVEAS            124
#define CMD_EXIT              125
#define CMD_ROTATE180         126
#define CMD_ROTATE_RIGHT      127
#define CMD_ROTATE_LEFT       128
#define CMD_FULLSCREEN        129
#define CMD_NEXTPAGE          130
#define CMD_PREVPAGE          131
#define CMD_FIRSTPAGE         132
#define CMD_LASTPAGE          133
#define CMD_PAGE              134
#define CMD_ZOOMWHOLE         135
#define CMD_ZOOMWIDTH         136
#define CMD_ZOOMACTUAL        137
#define CMD_ZOOMWINDOW        138
#define CMD_SELECTALL         139
#define CMD_DESELECT          140
#define CMD_HELP_CONTENTS     141
#define CMD_HELP_INDEX        142
#define CMD_HELP_SEARCH       143
//#define CMD_HELP_KEYBOARD     144
//#define CMD_HELP_MOUSE        145
#define CMD_FILE_PREV         146
#define CMD_FILE_NEXT         147
#define CMD_CAPTURE           148
#define CMD_TOOLS_HAND        149
#define CMD_TOOLS_ZOOM        150
#define CMD_TOOLS_SELECT      151
#define CMD_TOOLS_PIPETTE     152
#define CMD_PAGE_SETUP        153
#define CMD_PRINT             154
#define CMD_CROP              155
#define CMD_OPENREGISTRATION  156
#define CMD_TOOLBAR           157
#define CMD_STATUSBAR         158
#define CMD_CAPTURE_INTERNAL  159
#define CMD_V_PAGEUP          160
#define CMD_V_PAGEDOWN        161
#define CMD_V_HOME            162
#define CMD_V_END             163
#define CMD_H_PAGEUP          164
#define CMD_H_PAGEDOWN        165
#define CMD_H_HOME            166
#define CMD_H_END             167
#define CMD_CLOSE             168
#define CMD_UP                169
#define CMD_DOWN              170
#define CMD_LEFT              171
#define CMD_RIGHT             172
#define CMD_PAGE_INTERNAL     173
#define CMD_CAPTURE_CANCELED  174
#define CMD_WALLPAPER_CENTER  175
#define CMD_WALLPAPER_TILE    176
#define CMD_WALLPAPER_STRETCH 177
#define CMD_WALLPAPER_RESTORE 178
#define CMD_WALLPAPER_NONE    179
#define CMD_SCAN              180
#define CMD_SCAN_SOURCE       181
#define CMD_FILE_FIRST        182
#define CMD_FILE_LAST         183
#define CMD_IMG_FOCUS         184
#define CMD_IMG_RENAME        185
#define CMD_IMG_DELETE        186
#define CMD_INTERNAL_FOCUS    187
#define CMD_REGENERATE_THUMBNAIL 188
#define CMD_IMG_HISTOGRAM     189
#define CMD_FILE_TOGGLESELECT 190
#define CMD_FILE_PREVSELFILE  191
#define CMD_FILE_NEXTSELFILE  192
#define CMD_ZOOM_INMAX        193
#define CMD_IMG_COPYTO        194

// Petr: zakomentoval jsem, uz snad nebude nikdy potreba...
//#define CMD_INTERNAL_REFRESHLPANEL 195
//#define CMD_INTERNAL_REFRESHRPANEL 196

#define CMD_INTERNAL_REREADTHUMBS  197
#define CMD_INTERNAL_SAVEAS   198
#define CMD_INTERNAL_SCAN_EXTRA_IMAGES  199

// intervaly pro Recent Files/Directories
#define CMD_RECENTFILES_FIRST 460
#define CMD_RECENTFILES_LAST  469
#define CMD_RECENRDIRS_FIRST  470
#define CMD_RECENTDIRS_LAST   479

//
// Menu Helpers IDs
//

#define CML_FILE              480
#define CML_EDIT              481
#define CML_IMAGE             482
#define CML_VIEW              483
#define CML_TOOLS             484
#define CML_HELP              485
#define CML_MULTIPAGE         486
#define CML_RECENTFILES       487
#define CML_RECENTDIRS        488
#define CML_WALLPAPER         489
#define CML_OTHERFILES        490
#define CML_CONTEXT           491

//
// String Tables
//

#define IDS_MENU_FILE              500
#define IDS_MENU_FILE_OPEN         501
#define IDS_MENU_FILE_REFRESH      502
#define IDS_MENU_FILE_WALLPAPER    503
#define IDS_MENU_WALLPARER_CENTER  504
#define IDS_MENU_WALLPARER_TILE    505
#define IDS_MENU_WALLPARER_STRETCH 506
#define IDS_MENU_WALLPARER_RESTORE 507
#define IDS_MENU_WALLPARER_NONE    508
#define IDS_MENU_FILE_SAVEAS       509
#define IDS_MENU_FILE_PREV         510
#define IDS_MENU_FILE_NEXT         511
#define IDS_MENU_FILE_CAPTURE      512
#define IDS_MENU_FILE_PROP         513
#define IDS_MENU_FILE_PAGE         514
#define IDS_MENU_FILE_PRINT        515
#define IDS_MENU_FILE_FILES        516
#define IDS_MENU_FILE_DIRS         517
#define IDS_MENU_FILE_EXIT         518
#define IDS_MENU_FILE_SCAN         519
#define IDS_MENU_FILE_SCAN_SOURCE  520
#define IDS_MENU_FILE_OTHER        521
#define IDS_MENU_FILE_FIRST        522
#define IDS_MENU_FILE_LAST         523
#define IDS_MENU_FILE_FOCUS        524
#define IDS_MENU_FILE_RENAME       525
#define IDS_MENU_FILE_DELETE       526
#define IDS_MENU_FILE_EXIF         527
#define IDS_MENU_FILE_HISTOGRAM    528
#define IDS_MENU_FILE_SELCRCFILE   529
#define IDS_MENU_FILE_PREVSEL      550
#define IDS_MENU_FILE_NEXTSEL      551
#define IDS_MENU_FILE_COPYTO       552

#define IDS_MENU_EDIT            530
#define IDS_MENU_EDIT_COPY       531
#define IDS_MENU_EDIT_PASTE      532
#define IDS_MENU_EDIT_SELECTALL  533
#define IDS_MENU_EDIT_DESELECT   534
#define IDS_MENU_EDIT_CROP       535
#define IDS_MENU_EDIT_180        541
#define IDS_MENU_EDIT_RIGHT      542
#define IDS_MENU_EDIT_LEFT       543
#define IDS_MENU_EDIT_FLIPV      544
#define IDS_MENU_EDIT_FLIPH      545
// 550 az 552 jsou zabrane

#define IDS_MENU_VIEW            560
#define IDS_MENU_VIEW_ZOOMIN     561
#define IDS_MENU_VIEW_ZOOMOUT    562
#define IDS_MENU_VIEW_ZOOM       563
#define IDS_MENU_VIEW_FULLSCREEN 564
#define IDS_MENU_VIEW_WHOLE      565
#define IDS_MENU_VIEW_WIDTH      566
#define IDS_MENU_VIEW_ACTUAL     567
#define IDS_MENU_VIEW_WINDOW     568
#define IDS_MENU_VIEW_TOOLBAR    569
#define IDS_MENU_VIEW_STATUSBAR  570

#define IDS_MENU_TOOLS           580
#define IDS_MENU_TOOLS_HAND      581
#define IDS_MENU_TOOLS_ZOOM      582
#define IDS_MENU_TOOLS_SELECT    583
#define IDS_MENU_TOOLS_PICK      584
#define IDS_MENU_TOOLS_OPTIONS   585

#define IDS_MENU_HELP            590
#define IDS_MENU_HELP_CONTENTS   591
#define IDS_MENU_HELP_INDEX      592
#define IDS_MENU_HELP_SEARCH     593
#define IDS_MENU_HELP_KEYBOARD   594
#define IDS_MENU_HELP_MOUSE      595
#define IDS_MENU_HELP_ABOUT      596

#define IDS_MENU_MULTIPAGE       610
#define IDS_MENU_FIRSTPAGE       611
#define IDS_MENU_LASTPAGE        612
#define IDS_MENU_PAGE            613
#define IDS_MENU_NEXTPAGE        614
#define IDS_MENU_PREVPAGE        615

#define IDS_PLUGINNAME         999
#define IDS_LOWMEMORY         1000
#define IDS_SOME_WINS_OPENED  1002
#define IDS_ERROR_OPENING     1003
#define IDS_TITLE             1004
#define IDS_TITLE_MULTI       1005
#define IDS_NCOLORS           1006
#define IDS_NCOLORS_CMYK      1007
#define IDS_NCOLORS_LAB       1008
#define IDS_ERROR_CALLING_PVW32_DLL 1009
#define IDS_RGB               1010
#define IDS_RGB_HEX           1011
#define IDS_RGBXY             1012
#define IDS_RGBXY_HEX         1013
#define IDS_REGISTRATION_NUMOFLIC   1014
#define IDS_REGISTRATION_UNLIMITED  1015
#define IDS_REGISTRATION_EXPIRATION 1016
#define IDS_REGISTRATION_PRODUCTID  1017
#define IDS_REGISTRATION_EDUVERSION 1018
#define IDS_INDEX             1019
#define IDS_VIEW_BMP_IN_CLIPBOARD 1020
#define IDS_PIXELS            1021
#define IDS_BYTES             1022
#define IDS_OF                1023
#define IDS_FRAMES            1024
#define IDS_UNKNOWN           1025
#define IDS_CFG_CONFLICT      1026
#define IDS_CONFIGURATION_TITLE 1027
#define IDS_PLUGINSMENU_SCREEN_CAPTURE    1028
#define IDS_ERRORTITLE        1029
#define IDS_BADTIMER          1030
#define IDS_BADHOTKEY         1031
#define IDS_CAPTURECANCELED   1032
#define IDS_CAPTURING         1033
#define IDS_CLIPBOARD_TITLE   1034
#define IDS_CAPTURE_TITLE     1035
#define IDS_EMPTY             1036
#define IDS_OPENFILTER        1037
#define IDS_SCAN_TITLE        1038
#define IDS_SAVEASFILTERMONO  1039
#define IDS_SAVEASFILTERCOLOR 1040
#define IDS_SAVEERROR         1041
#define IDS_SAVE_AS_SUCCESS   1042
#define IDS_SAVE_LOST_ALPHA   1143
#define IDS_CUSTOM_COLOR      1043
#define IDS_AUTOMATIC_COLOR   1044
#define IDS_SAL_IS_BUSY       1045
#define IDS_RENAME_TO         1046
#define IDS_ERRORRENAMINGFILE 1047
#define IDS_TOOLONGNAME       1048
#define IDS_DELETED_TITLE     1049
#define IDS_LOADEXIF          1050
#define IDS_EXIF_TAG          1051
#define IDS_EXIF_VALUE        1052
#define IDS_EXIF_LOCALIZATION_FNAME 1142
#define IDS_CLIPBOARD_FNAME   1053
#define IDS_CAPTURE_FNAME     1054
#define IDS_SCAN_FNAME        1055
// Tooltips for capture dialog
#define IDS_CAPTHINT_APPL     1056
#define IDS_CAPTHINT_WINDOW   1057
#define IDS_CAPTHINT_CLIENT   1058

#define IDS_DONT_SHOW_AGAIN   1059
#define IDS_PLUGINSMENU_REGENERATE_THUMBNAIL  1060
#define IDS_REGENERATE_THUMBNAIL_TITLE 1061
#define IDS_REGENERATE_THUMB_WARNING   1062
#define IDS_REGENERATE_THUMB_WRITEFILE 1063

#define IDS_N_OF_N_FILES_PROCESSED     1064
#define IDS_NO_FILES_FOUND             1065
#define IDS_NOT_JPEG_FILE              1066
#define IDS_NOT_EXIF_CREATE_JFXX       1067
#define IDS_ERROR_OPENING_CONTINUE     1068
#define IDS_READ_ONLY_MODIFY           1069
#define IDS_READ_ONLY_REWRITE          1070

#define IDS_CLRS_MONO                  1071
#define IDS_CLRS_16                    1072
#define IDS_CLRS_256                   1073
#define IDS_CLRS_HC15                  1074
#define IDS_CLRS_HC16                  1075
#define IDS_CLRS_TC24                  1076
#define IDS_CLRS_TC32                  1077
#define IDS_CLRS_256GR                 1078

#define IDS_FLIP_NONE                  1079
#define IDS_FLIP_VERT                  1080
#define IDS_FLIP_HOR                   1081

#define IDS_ROT_NONE                   1082
#define IDS_ROT_90                     1083
#define IDS_ROT_180                    1084
#define IDS_ROT_270                    1085

#define IDS_HIST_HISTOGRAM      1086
#define IDS_HIST_LUMINOSITY     1087
#define IDS_HIST_RED            1088
#define IDS_HIST_GREEN          1089
#define IDS_HIST_BLUE           1090
#define IDS_HIST_RGBSUM         1091
#define IDS_HIST_MENU_LUMINOSITY 1092
#define IDS_HIST_MENU_RED       1093
#define IDS_HIST_MENU_GREEN     1094
#define IDS_HIST_MENU_BLUE      1095
#define IDS_HIST_MENU_RGBSUM    1096
#define IDS_HIST_TIP_LUMINOSITY 1097
#define IDS_HIST_TIP_RED        1098
#define IDS_HIST_TIP_GREEN      1099
#define IDS_HIST_TIP_BLUE       1100
#define IDS_HIST_TIP_RGBSUM     1101
#define IDS_HIST_TIP_OTHERCHANELS 1102

#define IDS_DLL_NOTFOUND        1109
#define IDS_DLL_WRONG_VERSION   1110
#define IDS_SELECT_REGION       1111

#define IDS_SAVE_DEFAULT              1112
#define IDS_SAVE_ERR_EXISTS_OVERWRITE 1113

#define IDS_PLUGIN_DESCRIPTION  1114

#define IDS_CANCELED_BY_USER    1115

#define IDS_NO_MORE_IMAGES      1116
#define IDS_IMGPROP_GRAY_NBIT   1117
#define IDS_UNSUPPORTED_IMAGE_TYPE 1118
#define IDS_MUSTBEPOSITIVE      1119

#define IDS_SB_XY               1120
#define IDS_SB_WH               1121
#define IDS_SB_RGB              1122
#define IDS_SB_TIP_SELECT_SQUARE 1129
#define IDS_SB_CAGE             1130
#define IDS_SB_ZOOM             1131
#define IDS_SB_HAND             1132

#define IDS_SB_AUTOROTATING     1133

// for Copy To dialog box
#define IDS_SELECTTARGETDIR     1140
#define IDS_SPECIFYPATH         1141

#define IDS_PICTVIEWPLUGINNAME  1145

#define IDS_DONT_SHOW_AGAIN_SLA 1146
#define IDS_DONT_SHOW_AGAIN_UTH 1147

#define IDS_PLUGINSMENU_SCAN    1148

#define IDS_WIA_ERROR_ACQUIREIMG            1160
#define IDS_WIA_WAIT                        1161
#define IDS_WIA_STATUS_TRANSFER_FROM_DEVICE 1162
#define IDS_WIA_STATUS_PROCESSING_DATA      1163
#define IDS_WIA_STATUS_TRANSFER_TO_CLIENT   1164

#define IDS_SCAN_OPEN_EXTRA_IMGS 1170

// Toolbar Tooltips
#define IDS_TT_OPEN              2200
#define IDS_TT_SAVE              2201
#define IDS_TT_PREV              2202
#define IDS_TT_NEXT              2203
#define IDS_TT_COPY              2204
#define IDS_TT_PASTE             2205
#define IDS_TT_TOOL_HAND         2206
#define IDS_TT_TOOL_ZOOM         2207
#define IDS_TT_TOOL_SELECT       2208
#define IDS_TT_TOOL_PIPETTE      2209
#define IDS_TT_LEFT              2210
#define IDS_TT_RIGHT             2211
#define IDS_TT_ZOOM_OUT          2212
#define IDS_TT_ZOOM_IN           2213
#define IDS_TT_ZOOM_TO           2214
#define IDS_TT_ZOOM_WIDTH        2215
#define IDS_TT_ZOOM_WHOLE        2216
#define IDS_TT_ZOOM_ACTUAL       2217
#define IDS_TT_FULL_SCREEN       2218
#define IDS_TT_PROPERTIES        2219
#define IDS_TT_SELSRCFILE        2220
#define IDS_TT_PREVSELFILE       2221
#define IDS_TT_NEXTSELFILE       2222
#define IDS_TT_CROP              2223
#define IDS_TT_PRINT             2224

// Twain strings
#define IDS_TWAIN_ERROR            2229
#define IDS_TWAIN_OPEN             2230
#define IDS_TWCC_BUMMER            2231 /* Failure due to unknown causes             */
#define IDS_TWCC_LOWMEMORY         2232 /* Not enough memory to perform operation    */
#define IDS_TWCC_NODS              2233 /* No Data Source                            */
#define IDS_TWCC_MAXCONNECTIONS    2234 /* DS is connected to max possible applications      */
#define IDS_TWCC_OPERATIONERROR    2235 /* DS or DSM reported error, application shouldn't   */
#define IDS_TWCC_BADCAP            2236 /* Unknown capability                        */
#define IDS_TWCC_BADPROTOCOL       2237 /* Unrecognized MSG DG DAT combination       */
#define IDS_TWCC_BADVALUE          2238 /* Data parameter out of range              */
#define IDS_TWCC_SEQERROR          2239 /* DG DAT MSG out of expected sequence      */
#define IDS_TWCC_BADDEST           2240 /* Unknown destination Application/Source in DSM_Entry */
#define IDS_TWCC_CAPUNSUPPORTED    2241 /* Capability not supported by source            */
#define IDS_TWCC_CAPBADOPERATION   2242 /* Operation not supported by capability         */
#define IDS_TWCC_CAPSEQERROR       2243 /* Capability has dependancy on other capability */
#define IDS_TWCC_DENIED            2244 /* File System operation is denied (file is protected) */
#define IDS_TWCC_FILEEXISTS        2245 /* Operation failed because file already exists. */
#define IDS_TWCC_FILENOTFOUND      2246 /* File not found */
#define IDS_TWCC_NOTEMPTY          2247 /* Operation failed because directory is not empty */
#define IDS_TWCC_PAPERJAM          2248  /* The feeder is jammed */
#define IDS_TWCC_PAPERDOUBLEFEED   2249  /* The feeder detected multiple pages */
#define IDS_TWCC_FILEWRITEERROR    2250  /* Error writing the file (meant for things like disk full conditions) */
#define IDS_TWCC_CHECKDEVICEONLINE 2251  /* The device went offline prior to or during this operation */

// print units
#define IDS_UNIT_INCHES            2280
#define IDS_UNIT_CM                2281
#define IDS_UNIT_MM                2282
#define IDS_UNIT_POINTS            2283
#define IDS_UNIT_PICAS             2284


// print dialog messages
#define IDS_PRINT_NODEFPRINTER     2290
#define IDS_PRINT_NOPRINTERS       2291
#define IDS_PRINT_SETUPFAILED      2292
#define IDS_PRINTING               2293
#define IDS_PRINTING_FAILED        2294
#define IDS_CHECK_EVENTLOG         2295
#define IDS_UNKNOWN_ERROR          2296

// licensing messages
#define IDS_LIC_CORRUPTED          2300
#define IDS_LIC_REG_ERROR          2301
#define IDS_LIC_EXPIRED            2302
#define IDS_LIC_SAL_UNREGISTERED   2303
#define IDS_LIC_WRONG_KEY          2304
#define IDS_EXCEPT_INFO1           2306
#define IDS_EXCEPT_INFO2           2307

// Texts for PVW32Cnv.dll - reserved IDs 4000-4999 !!!
#define IDS_DLL         4000

// IDcka stranek v html helpu
#define IDH_INTRODUCTION          3500
#define IDH_SCANIMAGE             3501
#define IDH_SCREENCAPTURE         3502
#define IDH_SELSCANNERSOURCE      3503
#define IDH_UPDATETHUMBNAIL       3504
#define IDH_VIEWBMPFROMCLIP       3505

// Save as dialog
#define IDD_SAVEEX                2300
#define IDC_SAVE_COMPRESSION_LABEL 2300
#define IDC_SAVE_COMPRESSION      2301
#define IDC_SAVE_ADVANCED         2302
#define IDC_SAVE_BIT_DEPTH        2303
#define IDC_SAVE_ROTATION         2304
#define IDC_SAVE_FLIP             2305
#define IDC_SAVE_INVERT           2307
#define IDC_SAVE_COMMENT_STATIC   2308
#define IDC_SAVE_COMMENT          2309
#define IDC_SAVE_COMMENT_FIRST    2308 // IDC_SAVE_COMMENT_STATIC
#define IDC_SAVE_COMMENT_LAST     2309 // IDC_SAVE_COMMENT
#define IDC_SAVE_GROUP_GIF        2310
#define IDC_SAVE_GIF_FIRST        2310 // IDC_SAVE_GROUP_GIF
#define IDC_SAVE_GIF_INTERLACED   2311
#define IDC_SAVE_GIF_89a          2312
#define IDC_SAVE_GIF_LAST         2312 // IDC_SAVE_GIF_89a
#define IDC_SAVE_GROUP_JPEG       2313
#define IDC_SAVE_JPEG_FIRST       2313 // IDC_SAVE_GROUP_JPEG
#define IDC_SAVE_JPEG_STATIC1     2314
#define IDC_SAVE_JPEG_QUALITY     2315
#define IDC_SAVE_JPEG_STATIC2     2316
#define IDC_SAVE_JPEG_STATIC3     2317
#define IDC_SAVE_JPEG_SUBSAMPLING 2318
#define IDC_SAVE_JPEG_LAST        2318 // IDC_SAVE_JPEG_SUBSAMPLING
#define IDC_SAVE_GROUP_TIFF       2319
#define IDC_SAVE_TIFF_FIRST       2319 // IDC_SAVE_GROUP_TIFF
#define IDC_SAVE_TIFF_MAKE_STRIPS 2320
#define IDC_SAVE_TIFF_STATIC1     2321
#define IDC_SAVE_TIFF_STRIP_SIZE  2322
#define IDC_SAVE_TIFF_STATIC2     2323
#define IDC_SAVE_TIFF_LAST        2323 // IDC_SAVE_TIFF_STATIC2
#define IDC_SAVE_LOWEST           2319 // IDC_SAVE_GROUP_TIFF
#define IDC_SAVE_ADVANCED_FIRST   2303 // IDC_SAVE_BIT_DEPTH
#define IDC_SAVE_ADVANCED_LAST    2323 // IDC_SAVE_TIFF_STATIC2
///* X:\ALTAP\PETR\salamand\plugins\pictview\pvw32cnv.rh2
// Petr: tento soubor existuje jen pro generovani symbols\plugins\pictview\symbols.inc davkou tools\export_altaptrl\export_inc.py

// Petr: pridal jsem IDS_PVW32Cnv_XXXX, aby nervala quiet-validace v Altap Translatoru
#define IDS_PVW32Cnv_4003          4003
#define IDS_PVW32Cnv_4004          4004
#define IDS_PVW32Cnv_4006          4006
#define IDS_PVW32Cnv_4007          4007
#define IDS_PVW32Cnv_4009          4009
#define IDS_PVW32Cnv_4015          4015
#define IDS_PVW32Cnv_4017          4017
#define IDS_PVW32Cnv_4019          4019
#define IDS_PVW32Cnv_4021          4021
#define IDS_PVW32Cnv_4027          4027
#define IDS_PVW32Cnv_4028          4028
#define IDS_PVW32Cnv_4029          4029
#define IDS_PVW32Cnv_4030          4030
#define IDS_PVW32Cnv_4037          4037
#define IDS_PVW32Cnv_4038          4038
#define IDS_PVW32Cnv_4039          4039
#define IDS_PVW32Cnv_4042          4042
#define IDS_PVW32Cnv_4043          4043
#define IDS_PVW32Cnv_4044          4044
#define IDS_PVW32Cnv_4049          4049
#define IDS_PVW32Cnv_4052          4052
#define IDS_PVW32Cnv_4056          4056
#define IDS_PVW32Cnv_4057          4057
#define IDS_PVW32Cnv_4058          4058
#define IDS_PVW32Cnv_4059          4059
#define IDS_PVW32Cnv_4063          4063
#define IDS_PVW32Cnv_4064          4064
#define IDS_PVW32Cnv_4065          4065
#define IDS_PVW32Cnv_4066          4066
#define IDS_PVW32Cnv_4067          4067
#define IDS_PVW32Cnv_4068          4068
#define IDS_PVW32Cnv_4069          4069
#define IDS_PVW32Cnv_4071          4071
#define IDS_PVW32Cnv_4073          4073
#define IDS_PVW32Cnv_4074          4074
#define IDS_PVW32Cnv_4075          4075
#define IDS_PVW32Cnv_4076          4076
#define IDS_PVW32Cnv_4077          4077
#define IDS_PVW32Cnv_4078          4078
#define IDS_PVW32Cnv_4079          4079
#define IDS_PVW32Cnv_4080          4080
#define IDS_PVW32Cnv_4081          4081
#define IDS_PVW32Cnv_4082          4082
#define IDS_PVW32Cnv_4083          4083
#define IDS_PVW32Cnv_4084          4084
#define IDS_PVW32Cnv_4085          4085
#define IDS_PVW32Cnv_4086          4086
#define IDS_PVW32Cnv_4087          4087
#define IDS_PVW32Cnv_4088          4088
#define IDS_PVW32Cnv_4089          4089
#define IDS_PVW32Cnv_4090          4090
#define IDS_PVW32Cnv_4091          4091
#define IDS_PVW32Cnv_4092          4092
#define IDS_PVW32Cnv_4093          4093
#define IDS_PVW32Cnv_4094          4094
#define IDS_PVW32Cnv_4096          4096
#define IDS_PVW32Cnv_4097          4097
#define IDS_PVW32Cnv_4099          4099
#define IDS_PVW32Cnv_4100          4100
#define IDS_PVW32Cnv_4102          4102
#define IDS_PVW32Cnv_4107          4107
#define IDS_PVW32Cnv_4108          4108
#define IDS_PVW32Cnv_4111          4111
#define IDS_PVW32Cnv_4112          4112
#define IDS_PVW32Cnv_4115          4115
#define IDS_PVW32Cnv_4117          4117
#define IDS_PVW32Cnv_4119          4119
#define IDS_PVW32Cnv_4120          4120
#define IDS_PVW32Cnv_4121          4121
#define IDS_PVW32Cnv_4122          4122
#define IDS_PVW32Cnv_4123          4123
#define IDS_PVW32Cnv_4124          4124
#define IDS_PVW32Cnv_4125          4125
#define IDS_PVW32Cnv_4126          4126
#define IDS_PVW32Cnv_4130          4130
#define IDS_PVW32Cnv_4165          4165
#define IDS_PVW32Cnv_4180          4180
#define IDS_PVW32Cnv_4195          4195
#define IDS_PVW32Cnv_4205          4205
#define IDS_PVW32Cnv_4206          4206
#define IDS_PVW32Cnv_4207          4207
#define IDS_PVW32Cnv_4209          4209
#define IDS_PVW32Cnv_4210          4210
#define IDS_PVW32Cnv_4219          4219
#define IDS_PVW32Cnv_4220          4220
#define IDS_PVW32Cnv_4223          4223
#define IDS_PVW32Cnv_4224          4224
#define IDS_PVW32Cnv_4232          4232
#define IDS_PVW32Cnv_4236          4236
#define IDS_PVW32Cnv_4241          4241
#define IDS_PVW32Cnv_4242          4242
#define IDS_PVW32Cnv_4243          4243
#define IDS_PVW32Cnv_4244          4244
#define IDS_PVW32Cnv_4245          4245
#define IDS_PVW32Cnv_4246          4246
#define IDS_PVW32Cnv_4248          4248
#define IDS_PVW32Cnv_4250          4250
#define IDS_PVW32Cnv_4252          4252
#define IDS_PVW32Cnv_4253          4253
#define IDS_PVW32Cnv_4254          4254
#define IDS_PVW32Cnv_4257          4257
#define IDS_PVW32Cnv_4259          4259
#define IDS_PVW32Cnv_4260          4260
#define IDS_PVW32Cnv_4261          4261
#define IDS_PVW32Cnv_4262          4262
#define IDS_PVW32Cnv_4263          4263
#define IDS_PVW32Cnv_4264          4264
#define IDS_PVW32Cnv_4265          4265
#define IDS_PVW32Cnv_4266          4266
#define IDS_PVW32Cnv_4269          4269
#define IDS_PVW32Cnv_4270          4270
#define IDS_PVW32Cnv_4271          4271
#define IDS_PVW32Cnv_4280          4280
#define IDS_PVW32Cnv_4281          4281
#define IDS_PVW32Cnv_4286          4286
#define IDS_PVW32Cnv_4287          4287
#define IDS_PVW32Cnv_4296          4296
#define IDS_PVW32Cnv_4297          4297
#define IDS_PVW32Cnv_4298          4298
#define IDS_PVW32Cnv_4299          4299
#define IDS_PVW32Cnv_4300          4300
#define IDS_PVW32Cnv_4301          4301
#define IDS_PVW32Cnv_4302          4302
#define IDS_PVW32Cnv_4303          4303
#define IDS_PVW32Cnv_4307          4307
#define IDS_PVW32Cnv_4308          4308
#define IDS_PVW32Cnv_4309          4309
#define IDS_PVW32Cnv_4310          4310
#define IDS_PVW32Cnv_4313          4313
#define IDS_PVW32Cnv_4315          4315
#define IDS_PVW32Cnv_4319          4319
#define IDS_PVW32Cnv_4322          4322
#define IDS_PVW32Cnv_4323          4323
#define IDS_PVW32Cnv_4324          4324
#define IDS_PVW32Cnv_4326          4326
#define IDS_PVW32Cnv_4329          4329
#define IDS_PVW32Cnv_4330          4330
#define IDS_PVW32Cnv_4331          4331
#define IDS_PVW32Cnv_4332          4332
#define IDS_PVW32Cnv_4340          4340
#define IDS_PVW32Cnv_4344          4344
#define IDS_PVW32Cnv_4345          4345
#define IDS_PVW32Cnv_4346          4346
#define IDS_PVW32Cnv_4347          4347
#define IDS_PVW32Cnv_4418          4418
///* X:\ALTAP\PETR\salamand\plugins\shared\statics.rh2
//#define IDC_STATIC_1        (IDC_STATIC_1+0) // definovano v nadrazenem headru
#define IDC_STATIC_2        (IDC_STATIC_1+1)
#define IDC_STATIC_3        (IDC_STATIC_1+2)
#define IDC_STATIC_4        (IDC_STATIC_1+3)
#define IDC_STATIC_5        (IDC_STATIC_1+4)
#define IDC_STATIC_6        (IDC_STATIC_1+5)
#define IDC_STATIC_7        (IDC_STATIC_1+6)
#define IDC_STATIC_8        (IDC_STATIC_1+7)
#define IDC_STATIC_9        (IDC_STATIC_1+8)
#define IDC_STATIC_10       (IDC_STATIC_1+9)
#define IDC_STATIC_11       (IDC_STATIC_1+10)
#define IDC_STATIC_12       (IDC_STATIC_1+11)
#define IDC_STATIC_13       (IDC_STATIC_1+12)
#define IDC_STATIC_14       (IDC_STATIC_1+13)
#define IDC_STATIC_15       (IDC_STATIC_1+14)
#define IDC_STATIC_16       (IDC_STATIC_1+15)
#define IDC_STATIC_17       (IDC_STATIC_1+16)
#define IDC_STATIC_18       (IDC_STATIC_1+17)
#define IDC_STATIC_19       (IDC_STATIC_1+18)
#define IDC_STATIC_20       (IDC_STATIC_1+19)
#define IDC_STATIC_21       (IDC_STATIC_1+20)
#define IDC_STATIC_22       (IDC_STATIC_1+21)
#define IDC_STATIC_23       (IDC_STATIC_1+22)
#define IDC_STATIC_24       (IDC_STATIC_1+23)
#define IDC_STATIC_25       (IDC_STATIC_1+24)
#define IDC_STATIC_26       (IDC_STATIC_1+25)
#define IDC_STATIC_27       (IDC_STATIC_1+26)
#define IDC_STATIC_28       (IDC_STATIC_1+27)
#define IDC_STATIC_29       (IDC_STATIC_1+28)
#define IDC_STATIC_30       (IDC_STATIC_1+29)
#define IDC_STATIC_31       (IDC_STATIC_1+30)
#define IDC_STATIC_32       (IDC_STATIC_1+31)
#define IDC_STATIC_33       (IDC_STATIC_1+32)
#define IDC_STATIC_34       (IDC_STATIC_1+33)
#define IDC_STATIC_35       (IDC_STATIC_1+34)
#define IDC_STATIC_36       (IDC_STATIC_1+35)
#define IDC_STATIC_37       (IDC_STATIC_1+36)
#define IDC_STATIC_38       (IDC_STATIC_1+37)
#define IDC_STATIC_39       (IDC_STATIC_1+38)
#define IDC_STATIC_40       (IDC_STATIC_1+39)
