// Defines for Altap Translator
#define IDOK                1
#define IDCANCEL            2
#define IDABORT             3
#define IDRETRY             4
#define IDIGNORE            5
#define IDYES               6
#define IDNO                7
#define IDCLOSE             8
#define IDHELP              9

///* X:\ALTAP\PETR\salamand\plugins\uncab\lang\lang.rh
//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by lang.rc
//
#define IDD_CHANGEDISK                  100
#define IDC_FILENAME                    101
#define IDC_BROWSE                      102
#define IDD_ERROR                       103
#define IDS_FILENAME                    104
#define IDC_DONTSHOW                    105
#define IDD_CONFIG                      106
#define IDC_SKIPCONTINUED               107
#define IDSKIP                          108
#define IDALL                           109
#define IDC_DISKNAME                    110
#define IDC_CABNAME                     111
#define IDC_TEXT                        112
#define IDD_WARNING                     115
#define IDC_NOVOLATTENTION              116

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        8500
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         8700
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
///* X:\ALTAP\PETR\salamand\plugins\uncab\uncab.rh2
#pragma once

#if defined(APSTUDIO_INVOKED) && !defined(APSTUDIO_READONLY_SYMBOLS)
#error this file is not editable by Microsoft Visual C++
#endif //defined(APSTUDIO_INVOKED) && !defined(APSTUDIO_READONLY_SYMBOLS)

#define IDC_STATIC_1 300
#include "statics.rh2"   // 300 az 339 jsou timto zabrane !!!

//***********************************************************************************
//
// texty
//

#define IDS_PLUGINNAME   1000
#define IDS_LOWMEM    1001
#define IDS_UNKNOWN   1008
#define IDS_BROWSEARCHIVETITLE 1012
#define IDS_LIST    1014
#define IDS_EXTRPROGTITLE 1015
#define IDS_PREPAREDATA   1016
#define IDS_EXTRACTFILES  1017
#define IDS_EXTRACTING    1018
#define IDS_UNABLEGETFIELPOS  1019
#define IDS_UNABLEWRITE   1020
#define IDS_UNABLESEEK    1021
#define IDS_TOOLONGNAME   1022
#define IDS_TOOLONGMASK   1023
#define IDS_EXPIRE      1025
#define IDS_UNABLECREATE  1026
#define IDS_UNABLEREAD    1027
#define IDS_CABINET_NOT_FOUND 1028
#define IDS_NOT_A_CABINET 1029
#define IDS_UNKNOWN_CABINET_VERSION 1030
#define IDS_CORRUPT_CABINET 1031
#define IDS_BAD_COMPR_TYPE  1032
#define IDS_MDI_FAIL    1033
#define IDS_RESERVE_MISMATCH  1034
#define IDS_USER_ABORT    1035
#define IDS_BROWSEFOLDERTEXT  1036
#define IDS_WRONG_CABINET 1037
#define IDS_NOTFOUND    1038
#define IDS_SKIPPING    1039
#define IDS_NEXTVOLTEXT   1040
#define IDS_ERROR   1041
#define IDS_PLUGIN_DESCRIPTION  1042
#define IDS_ABOUT               1043

//***********************************************************************************
//
// ikony
//
#define IDI_LOCK  500
///* X:\ALTAP\PETR\salamand\plugins\shared\statics.rh2
//#define IDC_STATIC_1        (IDC_STATIC_1+0) // definovano v nadrazenem headru
#define IDC_STATIC_2        (IDC_STATIC_1+1)
#define IDC_STATIC_3        (IDC_STATIC_1+2)
#define IDC_STATIC_4        (IDC_STATIC_1+3)
#define IDC_STATIC_5        (IDC_STATIC_1+4)
#define IDC_STATIC_6        (IDC_STATIC_1+5)
#define IDC_STATIC_7        (IDC_STATIC_1+6)
#define IDC_STATIC_8        (IDC_STATIC_1+7)
#define IDC_STATIC_9        (IDC_STATIC_1+8)
#define IDC_STATIC_10       (IDC_STATIC_1+9)
#define IDC_STATIC_11       (IDC_STATIC_1+10)
#define IDC_STATIC_12       (IDC_STATIC_1+11)
#define IDC_STATIC_13       (IDC_STATIC_1+12)
#define IDC_STATIC_14       (IDC_STATIC_1+13)
#define IDC_STATIC_15       (IDC_STATIC_1+14)
#define IDC_STATIC_16       (IDC_STATIC_1+15)
#define IDC_STATIC_17       (IDC_STATIC_1+16)
#define IDC_STATIC_18       (IDC_STATIC_1+17)
#define IDC_STATIC_19       (IDC_STATIC_1+18)
#define IDC_STATIC_20       (IDC_STATIC_1+19)
#define IDC_STATIC_21       (IDC_STATIC_1+20)
#define IDC_STATIC_22       (IDC_STATIC_1+21)
#define IDC_STATIC_23       (IDC_STATIC_1+22)
#define IDC_STATIC_24       (IDC_STATIC_1+23)
#define IDC_STATIC_25       (IDC_STATIC_1+24)
#define IDC_STATIC_26       (IDC_STATIC_1+25)
#define IDC_STATIC_27       (IDC_STATIC_1+26)
#define IDC_STATIC_28       (IDC_STATIC_1+27)
#define IDC_STATIC_29       (IDC_STATIC_1+28)
#define IDC_STATIC_30       (IDC_STATIC_1+29)
#define IDC_STATIC_31       (IDC_STATIC_1+30)
#define IDC_STATIC_32       (IDC_STATIC_1+31)
#define IDC_STATIC_33       (IDC_STATIC_1+32)
#define IDC_STATIC_34       (IDC_STATIC_1+33)
#define IDC_STATIC_35       (IDC_STATIC_1+34)
#define IDC_STATIC_36       (IDC_STATIC_1+35)
#define IDC_STATIC_37       (IDC_STATIC_1+36)
#define IDC_STATIC_38       (IDC_STATIC_1+37)
#define IDC_STATIC_39       (IDC_STATIC_1+38)
#define IDC_STATIC_40       (IDC_STATIC_1+39)
