// Defines for Altap Translator
#define IDOK                1
#define IDCANCEL            2
#define IDABORT             3
#define IDRETRY             4
#define IDIGNORE            5
#define IDYES               6
#define IDNO                7
#define IDCLOSE             8
#define IDHELP              9

///* X:\ALTAP\PETR\salamand\plugins\unlha\lang\lang.rh
//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by lang.rc
//

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        8500
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         8700
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
///* X:\ALTAP\PETR\salamand\plugins\unlha\unlha.rh2
#pragma once

#if defined(APSTUDIO_INVOKED) && !defined(APSTUDIO_READONLY_SYMBOLS)
#error this file is not editable by Microsoft Visual C++
#endif //defined(APSTUDIO_INVOKED) && !defined(APSTUDIO_READONLY_SYMBOLS)

// ********************************************************************************
//
//  TEXTY
//

#define IDS_FILECORRUPT                 1
#define IDS_CHECKSUMERROR               2
#define IDS_LOWMEM                      3
#define IDS_WRITEERROR                  4
#define IDS_PLUGINNAME                  5
#define IDS_OPENERROR                   6
#define IDS_LIST                        7
#define IDS_SYMLINK                     8
#define IDS_UNPACKERROR                 10
#define IDS_CRCERROR                    11
#define IDS_READERROR                   12
#define IDS_EXTRPROGTITLE               13
#define IDS_PREPAREDATA                 14
#define IDS_UNPACKING                   15
#define IDS_EXTRACTFILES                16
#define IDS_TOOLONGNAME                 17
#define IDS_TOOLONGMASK                 18
#define IDS_METHOD                      19
#define IDS_METHOD2                     20
#define IDS_PLUGIN_DESCRIPTION          21
#define IDS_ABOUT                       22
