rem
rem Odstrani ze stromu 7z313 soubory, ktere nejsou potreba pro kompilovani 7za.dll
rem

rem nejdriv smazneme soubory

del /Q 7zip\Archive\7z\7z.dsp
del /Q 7zip\Archive\7z\7z.dsw
del /Q 7zip\Archive\Arj\Arj.def
del /Q 7zip\Archive\Arj\Arj.dsp
del /Q 7zip\Archive\Arj\Arj.dsw
del /Q 7zip\Archive\Arj\arj.ico
del /Q 7zip\Archive\Arj\ArjHandler.cpp
del /Q 7zip\Archive\Arj\ArjHandler.h
del /Q 7zip\Archive\Arj\ArjHeader.h
del /Q 7zip\Archive\Arj\ArjIn.cpp
del /Q 7zip\Archive\Arj\ArjIn.h
del /Q 7zip\Archive\Arj\ArjItem.h
del /Q 7zip\Archive\Arj\DllExports.cpp
del /Q 7zip\Archive\Arj\resource.h
del /Q 7zip\Archive\Arj\resource.rc
del /Q 7zip\Archive\Arj\StdAfx.cpp
del /Q 7zip\Archive\Arj\StdAfx.h
del /Q 7zip\Archive\BZip2\bz2.ico
del /Q 7zip\Archive\BZip2\BZip2.def
del /Q 7zip\Archive\BZip2\BZip2.dsp
del /Q 7zip\Archive\BZip2\BZip2.dsw
del /Q 7zip\Archive\BZip2\BZip2Handler.cpp
del /Q 7zip\Archive\BZip2\BZip2Handler.h
del /Q 7zip\Archive\BZip2\BZip2HandlerOut.cpp
del /Q 7zip\Archive\BZip2\BZip2Item.h
del /Q 7zip\Archive\BZip2\BZip2Update.cpp
del /Q 7zip\Archive\BZip2\BZip2Update.h
del /Q 7zip\Archive\BZip2\DllExports.cpp
del /Q 7zip\Archive\BZip2\resource.h
del /Q 7zip\Archive\BZip2\resource.rc
del /Q 7zip\Archive\BZip2\StdAfx.cpp
del /Q 7zip\Archive\BZip2\StdAfx.h
del /Q 7zip\Archive\Cab\Cab.def
del /Q 7zip\Archive\Cab\Cab.dsp
del /Q 7zip\Archive\Cab\Cab.dsw
del /Q 7zip\Archive\Cab\cab.ico
del /Q 7zip\Archive\Cab\CabCopyDecoder.cpp
del /Q 7zip\Archive\Cab\CabCopyDecoder.h
del /Q 7zip\Archive\Cab\CabHandler.cpp
del /Q 7zip\Archive\Cab\CabHandler.h
del /Q 7zip\Archive\Cab\CabHeader.cpp
del /Q 7zip\Archive\Cab\CabHeader.h
del /Q 7zip\Archive\Cab\CabIn.cpp
del /Q 7zip\Archive\Cab\CabIn.h
del /Q 7zip\Archive\Cab\CabInBuffer.cpp
del /Q 7zip\Archive\Cab\CabInBuffer.h
del /Q 7zip\Archive\Cab\CabItem.h
del /Q 7zip\Archive\Cab\DllExports.cpp
del /Q 7zip\Archive\Cab\LZXBitDecoder.h
del /Q 7zip\Archive\Cab\LZXConst.h
del /Q 7zip\Archive\Cab\LZXDecoder.cpp
del /Q 7zip\Archive\Cab\LZXDecoder.h
del /Q 7zip\Archive\Cab\LZXExtConst.h
del /Q 7zip\Archive\Cab\LZXi86Converter.cpp
del /Q 7zip\Archive\Cab\LZXi86Converter.h
del /Q 7zip\Archive\Cab\MSZipConst.h
del /Q 7zip\Archive\Cab\MSZipDecoder.cpp
del /Q 7zip\Archive\Cab\MSZipDecoder.h
del /Q 7zip\Archive\Cab\MSZipExtConst.h
del /Q 7zip\Archive\Cab\resource.h
del /Q 7zip\Archive\Cab\resource.rc
del /Q 7zip\Archive\Cab\StdAfx.cpp
del /Q 7zip\Archive\Cab\StdAfx.h
del /Q 7zip\Archive\Common\CodecsPath.h
del /Q 7zip\Archive\Common\CodecsPath.cpp
del /Q 7zip\Archive\Common\CoderLoader.h
del /Q 7zip\Archive\Common\CoderMixer.cpp
del /Q 7zip\Archive\Common\CoderMixer.h
del /Q 7zip\Archive\Common\CoderPaths.cpp
del /Q 7zip\Archive\Common\DummyOutStream.cpp
del /Q 7zip\Archive\Common\DummyOutStream.h
del /Q 7zip\Archive\Common\StdAfx.h
del /Q 7zip\Archive\cpio\cpio.def
del /Q 7zip\Archive\cpio\cpio.dsp
del /Q 7zip\Archive\cpio\cpio.dsw
del /Q 7zip\Archive\cpio\cpio.ico
del /Q 7zip\Archive\cpio\CpioHandler.cpp
del /Q 7zip\Archive\cpio\CpioHandler.h
del /Q 7zip\Archive\cpio\CpioHeader.cpp
del /Q 7zip\Archive\cpio\CpioHeader.h
del /Q 7zip\Archive\cpio\CpioIn.cpp
del /Q 7zip\Archive\cpio\CpioIn.h
del /Q 7zip\Archive\cpio\CpioItem.h
del /Q 7zip\Archive\cpio\DllExports.cpp
del /Q 7zip\Archive\cpio\resource.h
del /Q 7zip\Archive\cpio\resource.rc
del /Q 7zip\Archive\cpio\StdAfx.cpp
del /Q 7zip\Archive\cpio\StdAfx.h
del /Q 7zip\Archive\Deb\Deb.def
del /Q 7zip\Archive\Deb\Deb.dsp
del /Q 7zip\Archive\Deb\Deb.dsw
del /Q 7zip\Archive\Deb\deb.ico
del /Q 7zip\Archive\Deb\DebHandler.cpp
del /Q 7zip\Archive\Deb\DebHandler.h
del /Q 7zip\Archive\Deb\DebHeader.cpp
del /Q 7zip\Archive\Deb\DebHeader.h
del /Q 7zip\Archive\Deb\DebIn.cpp
del /Q 7zip\Archive\Deb\DebIn.h
del /Q 7zip\Archive\Deb\DebItem.h
del /Q 7zip\Archive\Deb\DllExports.cpp
del /Q 7zip\Archive\Deb\resource.h
del /Q 7zip\Archive\Deb\resource.rc
del /Q 7zip\Archive\Deb\StdAfx.cpp
del /Q 7zip\Archive\Deb\StdAfx.h
del /Q 7zip\Archive\GZip\DllExports.cpp
del /Q 7zip\Archive\GZip\gz.ico
del /Q 7zip\Archive\GZip\GZip.def
del /Q 7zip\Archive\GZip\GZip.dsp
del /Q 7zip\Archive\GZip\GZip.dsw
del /Q 7zip\Archive\GZip\GZipHandler.cpp
del /Q 7zip\Archive\GZip\GZipHandler.h
del /Q 7zip\Archive\GZip\GZipHandlerOut.cpp
del /Q 7zip\Archive\GZip\GZipHeader.cpp
del /Q 7zip\Archive\GZip\GZipHeader.h
del /Q 7zip\Archive\GZip\GZipIn.cpp
del /Q 7zip\Archive\GZip\GZipIn.h
del /Q 7zip\Archive\GZip\GZipItem.h
del /Q 7zip\Archive\GZip\GZipOut.cpp
del /Q 7zip\Archive\GZip\GZipOut.h
del /Q 7zip\Archive\GZip\GZipUpdate.cpp
del /Q 7zip\Archive\GZip\GZipUpdate.h
del /Q 7zip\Archive\GZip\resource.h
del /Q 7zip\Archive\GZip\resource.rc
del /Q 7zip\Archive\GZip\StdAfx.cpp
del /Q 7zip\Archive\GZip\StdAfx.h
del /Q 7zip\Archive\Rar\DllExports.cpp
del /Q 7zip\Archive\Rar\Rar.def
del /Q 7zip\Archive\Rar\Rar.dsp
del /Q 7zip\Archive\Rar\Rar.dsw
del /Q 7zip\Archive\Rar\rar.ico
del /Q 7zip\Archive\Rar\RarHandler.cpp
del /Q 7zip\Archive\Rar\RarHandler.h
del /Q 7zip\Archive\Rar\RarHeader.cpp
del /Q 7zip\Archive\Rar\RarHeader.h
del /Q 7zip\Archive\Rar\RarIn.cpp
del /Q 7zip\Archive\Rar\RarIn.h
del /Q 7zip\Archive\Rar\RarItem.cpp
del /Q 7zip\Archive\Rar\RarItem.h
del /Q 7zip\Archive\Rar\RarItemEx.h
del /Q 7zip\Archive\Rar\RarVolumeInStream.cpp
del /Q 7zip\Archive\Rar\RarVolumeInStream.h
del /Q 7zip\Archive\Rar\resource.h
del /Q 7zip\Archive\Rar\resource.rc
del /Q 7zip\Archive\Rar\StdAfx.cpp
del /Q 7zip\Archive\Rar\StdAfx.h
del /Q 7zip\Archive\RPM\DllExports.cpp
del /Q 7zip\Archive\RPM\resource.h
del /Q 7zip\Archive\RPM\resource.rc
del /Q 7zip\Archive\RPM\Rpm.def
del /Q 7zip\Archive\RPM\Rpm.dsp
del /Q 7zip\Archive\RPM\Rpm.dsw
del /Q 7zip\Archive\RPM\rpm.ico
del /Q 7zip\Archive\RPM\RpmHandler.cpp
del /Q 7zip\Archive\RPM\RpmHandler.h
del /Q 7zip\Archive\RPM\RpmHeader.h
del /Q 7zip\Archive\RPM\RpmIn.cpp
del /Q 7zip\Archive\RPM\RpmIn.h
del /Q 7zip\Archive\RPM\StdAfx.cpp
del /Q 7zip\Archive\RPM\StdAfx.h
del /Q 7zip\Archive\Split\DllExports.cpp
del /Q 7zip\Archive\Split\resource.h
del /Q 7zip\Archive\Split\resource.rc
del /Q 7zip\Archive\Split\Split.def
del /Q 7zip\Archive\Split\Split.dsp
del /Q 7zip\Archive\Split\Split.dsw
del /Q 7zip\Archive\Split\Split.ico
del /Q 7zip\Archive\Split\SplitHandler.cpp
del /Q 7zip\Archive\Split\SplitHandler.h
del /Q 7zip\Archive\Split\SplitHanlerOut.cpp
del /Q 7zip\Archive\Split\StdAfx.cpp
del /Q 7zip\Archive\Split\StdAfx.h
del /Q 7zip\Archive\Tar\DllExports.cpp
del /Q 7zip\Archive\Tar\resource.h
del /Q 7zip\Archive\Tar\resource.rc
del /Q 7zip\Archive\Tar\StdAfx.cpp
del /Q 7zip\Archive\Tar\StdAfx.h
del /Q 7zip\Archive\Tar\Tar.def
del /Q 7zip\Archive\Tar\Tar.dsp
del /Q 7zip\Archive\Tar\Tar.dsw
del /Q 7zip\Archive\Tar\tar.ico
del /Q 7zip\Archive\Tar\TarHandler.cpp
del /Q 7zip\Archive\Tar\TarHandler.h
del /Q 7zip\Archive\Tar\TarHandlerOut.cpp
del /Q 7zip\Archive\Tar\TarHeader.cpp
del /Q 7zip\Archive\Tar\TarHeader.h
del /Q 7zip\Archive\Tar\TarIn.cpp
del /Q 7zip\Archive\Tar\TarIn.h
del /Q 7zip\Archive\Tar\TarItem.h
del /Q 7zip\Archive\Tar\TarOut.cpp
del /Q 7zip\Archive\Tar\TarOut.h
del /Q 7zip\Archive\Tar\TarUpdate.cpp
del /Q 7zip\Archive\Tar\TarUpdate.h
del /Q 7zip\Archive\Zip\DllExports.cpp
del /Q 7zip\Archive\Zip\resource.h
del /Q 7zip\Archive\Zip\resource.rc
del /Q 7zip\Archive\Zip\StdAfx.cpp
del /Q 7zip\Archive\Zip\StdAfx.h
del /Q 7zip\Archive\Zip\Zip.def
del /Q 7zip\Archive\Zip\Zip.dsp
del /Q 7zip\Archive\Zip\Zip.dsw
del /Q 7zip\Archive\Zip\zip.ico
del /Q 7zip\Archive\Zip\ZipAddCommon.cpp
del /Q 7zip\Archive\Zip\ZipAddCommon.h
del /Q 7zip\Archive\Zip\ZipCompressionMode.h
del /Q 7zip\Archive\Zip\ZipHandler.cpp
del /Q 7zip\Archive\Zip\ZipHandler.h
del /Q 7zip\Archive\Zip\ZipHandlerOut.cpp
del /Q 7zip\Archive\Zip\ZipHeader.cpp
del /Q 7zip\Archive\Zip\ZipHeader.h
del /Q 7zip\Archive\Zip\ZipIn.cpp
del /Q 7zip\Archive\Zip\ZipIn.h
del /Q 7zip\Archive\Zip\ZipItem.cpp
del /Q 7zip\Archive\Zip\ZipItem.h
del /Q 7zip\Archive\Zip\ZipItemEx.h
del /Q 7zip\Archive\Zip\ZipOut.cpp
del /Q 7zip\Archive\Zip\ZipOut.h
del /Q 7zip\Archive\Zip\ZipUpdate.cpp
del /Q 7zip\Archive\Zip\ZipUpdate.h
del /Q 7zip\Bundles\Alone\afxres.h
del /Q 7zip\Bundles\Alone\Alone.dsp
del /Q 7zip\Bundles\Alone\Alone.dsw
del /Q 7zip\Bundles\Alone\resource.h
del /Q 7zip\Bundles\Alone\resource.rc
del /Q 7zip\Bundles\Alone\StdAfx.cpp
del /Q 7zip\Bundles\Alone\StdAfx.h
del /Q 7zip\Bundles\Format7z\Format7z.dsp
del /Q 7zip\Bundles\Format7z\Format7z.dsw
del /Q 7zip\Bundles\SFXCon\7z.ico
del /Q 7zip\Bundles\SFXCon\Main.cpp
del /Q 7zip\Bundles\SFXCon\resource.h
del /Q 7zip\Bundles\SFXCon\resource.rc
del /Q 7zip\Bundles\SFXCon\SFXCon.dsp
del /Q 7zip\Bundles\SFXCon\SFXCon.dsw
del /Q 7zip\Bundles\SFXCon\StdAfx.cpp
del /Q 7zip\Bundles\SFXCon\StdAfx.h
del /Q 7zip\Bundles\SFXSetup\ExtractCallback.cpp
del /Q 7zip\Bundles\SFXSetup\ExtractCallback.h
del /Q 7zip\Bundles\SFXSetup\ExtractEngine.cpp
del /Q 7zip\Bundles\SFXSetup\ExtractEngine.h
del /Q 7zip\Bundles\SFXSetup\Main.cpp
del /Q 7zip\Bundles\SFXSetup\resource.h
del /Q 7zip\Bundles\SFXSetup\resource.rc
del /Q 7zip\Bundles\SFXSetup\setup.ico
del /Q 7zip\Bundles\SFXSetup\SFXSetup.dsp
del /Q 7zip\Bundles\SFXSetup\SFXSetup.dsw
del /Q 7zip\Bundles\SFXSetup\StdAfx.cpp
del /Q 7zip\Bundles\SFXSetup\StdAfx.h
del /Q 7zip\Bundles\SFXWin\7z.ico
del /Q 7zip\Bundles\SFXWin\Main.cpp
del /Q 7zip\Bundles\SFXWin\resource.h
del /Q 7zip\Bundles\SFXWin\resource.rc
del /Q 7zip\Bundles\SFXWin\SFXWin.dsp
del /Q 7zip\Bundles\SFXWin\SFXWin.dsw
del /Q 7zip\Bundles\SFXWin\StdAfx.cpp
del /Q 7zip\Bundles\SFXWin\StdAfx.h
del /Q 7zip\Common\FilePathAutoRename.cpp
del /Q 7zip\Common\FilePathAutoRename.h
del /Q 7zip\Common\LSBFDecoder.cpp
del /Q 7zip\Common\LSBFDecoder.h
del /Q 7zip\Common\LSBFEncoder.cpp
del /Q 7zip\Common\LSBFEncoder.h
del /Q 7zip\Common\MSBFDecoder.h
del /Q 7zip\Common\MSBFEncoder.h
del /Q 7zip\Common\OffsetStream.cpp
del /Q 7zip\Common\OffsetStream.h
del /Q 7zip\Compress\Arj\Decoder1.cpp
del /Q 7zip\Compress\Arj\Decoder1.h
del /Q 7zip\Compress\Arj\Decoder2.cpp
del /Q 7zip\Compress\Arj\Decoder2.h
del /Q 7zip\Compress\Branch\Alpha.cpp
del /Q 7zip\Compress\Branch\Alpha.h
del /Q 7zip\Compress\Branch\ARM.cpp
del /Q 7zip\Compress\Branch\ARM.h
del /Q 7zip\Compress\Branch\ARMThumb.cpp
del /Q 7zip\Compress\Branch\ARMThumb.h
del /Q 7zip\Compress\Branch\Branch.def
del /Q 7zip\Compress\Branch\Branch.dsp
del /Q 7zip\Compress\Branch\Branch.dsw
del /Q 7zip\Compress\Branch\DllExports.cpp
del /Q 7zip\Compress\Branch\IA64.cpp
del /Q 7zip\Compress\Branch\IA64.h
del /Q 7zip\Compress\Branch\M68.cpp
del /Q 7zip\Compress\Branch\M68.h
del /Q 7zip\Compress\Branch\PPC.cpp
del /Q 7zip\Compress\Branch\PPC.h
del /Q 7zip\Compress\Branch\resource.h
del /Q 7zip\Compress\Branch\resource.rc
del /Q 7zip\Compress\ByteSwap\ByteSwap.cpp
del /Q 7zip\Compress\ByteSwap\ByteSwap.def
del /Q 7zip\Compress\ByteSwap\ByteSwap.dsp
del /Q 7zip\Compress\ByteSwap\ByteSwap.dsw
del /Q 7zip\Compress\ByteSwap\ByteSwap.h
del /Q 7zip\Compress\ByteSwap\DllExports.cpp
del /Q 7zip\Compress\ByteSwap\resource.h
del /Q 7zip\Compress\ByteSwap\resource.rc
del /Q 7zip\Compress\ByteSwap\StdAfx.cpp
del /Q 7zip\Compress\ByteSwap\StdAfx.h
del /Q 7zip\Compress\BZip2\BZip2.def
del /Q 7zip\Compress\BZip2\BZip2.dsp
del /Q 7zip\Compress\BZip2\BZip2.dsw
del /Q 7zip\Compress\BZip2\BZip2Decoder.cpp
del /Q 7zip\Compress\BZip2\BZip2Decoder.h
del /Q 7zip\Compress\BZip2\BZip2Encoder.cpp
del /Q 7zip\Compress\BZip2\BZip2Encoder.h
del /Q 7zip\Compress\BZip2\BZip2Error.cpp
del /Q 7zip\Compress\BZip2\DllExports.cpp
del /Q 7zip\Compress\BZip2\resource.h
del /Q 7zip\Compress\BZip2\resource.rc
del /Q 7zip\Compress\BZip2\StdAfx.cpp
del /Q 7zip\Compress\BZip2\StdAfx.h
del /Q 7zip\Compress\Copy\Copy.def
del /Q 7zip\Compress\Copy\Copy.dsp
del /Q 7zip\Compress\Copy\Copy.dsw
del /Q 7zip\Compress\Copy\DllExports.cpp
del /Q 7zip\Compress\Copy\resource.h
del /Q 7zip\Compress\Copy\resource.rc
del /Q 7zip\Compress\Deflate\Deflate.def
del /Q 7zip\Compress\Deflate\Deflate.dsp
del /Q 7zip\Compress\Deflate\Deflate.dsw
del /Q 7zip\Compress\Deflate\DeflateConst.h
del /Q 7zip\Compress\Deflate\DeflateDecoder.cpp
del /Q 7zip\Compress\Deflate\DeflateDecoder.h
del /Q 7zip\Compress\Deflate\DeflateEncoder.cpp
del /Q 7zip\Compress\Deflate\DeflateEncoder.h
del /Q 7zip\Compress\Deflate\DeflateExtConst.h
del /Q 7zip\Compress\Deflate\DllExports.cpp
del /Q 7zip\Compress\Deflate\resource.h
del /Q 7zip\Compress\Deflate\resource.rc
del /Q 7zip\Compress\Deflate\StdAfx.cpp
del /Q 7zip\Compress\Deflate\StdAfx.h
del /Q 7zip\Compress\Huffman\HuffmanDecoder.h
del /Q 7zip\Compress\Huffman\HuffmanEncoder.cpp
del /Q 7zip\Compress\Huffman\HuffmanEncoder.h
del /Q 7zip\Compress\Huffman\StdAfx.h
del /Q 7zip\Compress\Implode\DllExports.cpp
del /Q 7zip\Compress\Implode\Implode.def
del /Q 7zip\Compress\Implode\Implode.dsp
del /Q 7zip\Compress\Implode\Implode.dsw
del /Q 7zip\Compress\Implode\ImplodeDecoder.cpp
del /Q 7zip\Compress\Implode\ImplodeDecoder.h
del /Q 7zip\Compress\Implode\ImplodeHuffmanDecoder.cpp
del /Q 7zip\Compress\Implode\ImplodeHuffmanDecoder.h
del /Q 7zip\Compress\Implode\resource.h
del /Q 7zip\Compress\Implode\resource.rc
del /Q 7zip\Compress\Implode\StdAfx.cpp
del /Q 7zip\Compress\Implode\StdAfx.h
del /Q 7zip\Compress\LZ\BinTree\BinTree3Z.h
del /Q 7zip\Compress\LZ\BinTree\BinTree3ZMain.h
del /Q 7zip\Compress\LZ\HashChain\HC2.h
del /Q 7zip\Compress\LZ\HashChain\HC4b.h
del /Q 7zip\Compress\LZMA\DllExports.cpp
del /Q 7zip\Compress\LZMA\LZMA.def
del /Q 7zip\Compress\LZMA\LZMA.dsp
del /Q 7zip\Compress\LZMA\LZMA.dsw
del /Q 7zip\Compress\LZMA\resource.h
del /Q 7zip\Compress\LZMA\resource.rc
del /Q 7zip\Compress\PPMD\DllExports.cpp
del /Q 7zip\Compress\PPMD\PPMD.def
del /Q 7zip\Compress\PPMD\PPMD.dsp
del /Q 7zip\Compress\PPMD\PPMD.dsw
del /Q 7zip\Compress\PPMD\resource.h
del /Q 7zip\Compress\PPMD\resource.rc
del /Q 7zip\Crypto\7zAES\7zAES.def
del /Q 7zip\Crypto\7zAES\7zAES.dsp
del /Q 7zip\Crypto\7zAES\7zAES.dsw
del /Q 7zip\Crypto\7zAES\DllExports.cpp
del /Q 7zip\Crypto\7zAES\resource.h
del /Q 7zip\Crypto\7zAES\resource.rc
del /Q 7zip\Crypto\AES\AES.def
del /Q 7zip\Crypto\AES\AES.dsp
del /Q 7zip\Crypto\AES\AES.dsw
del /Q 7zip\Crypto\AES\DllExports.cpp
del /Q 7zip\Crypto\AES\resource.h
del /Q 7zip\Crypto\AES\resource.rc
del /Q 7zip\Crypto\Rar20\Rar20Cipher.cpp
del /Q 7zip\Crypto\Rar20\Rar20Cipher.h
del /Q 7zip\Crypto\Rar20\Rar20Crypto.cpp
del /Q 7zip\Crypto\Rar20\Rar20Crypto.h
del /Q 7zip\Crypto\RarAES\RarAES.cpp
del /Q 7zip\Crypto\RarAES\RarAES.h
del /Q 7zip\Crypto\RarAES\sha1.cpp
del /Q 7zip\Crypto\RarAES\sha1.h
del /Q 7zip\Crypto\Zip\StdAfx.h
del /Q 7zip\Crypto\Zip\ZipCipher.cpp
del /Q 7zip\Crypto\Zip\ZipCipher.h
del /Q 7zip\Crypto\Zip\ZipCrypto.cpp
del /Q 7zip\Crypto\Zip\ZipCrypto.h
del /Q 7zip\FileManager\7zFM.exe.manifest
del /Q 7zip\FileManager\7zipLogo.ico
del /Q 7zip\FileManager\Add.bmp
del /Q 7zip\FileManager\Add2.bmp
del /Q 7zip\FileManager\App.cpp
del /Q 7zip\FileManager\App.h
del /Q 7zip\FileManager\AppState.h
del /Q 7zip\FileManager\ClassDefs.cpp
del /Q 7zip\FileManager\Copy.bmp
del /Q 7zip\FileManager\Copy2.bmp
del /Q 7zip\FileManager\Delete.bmp
del /Q 7zip\FileManager\Delete2.bmp
del /Q 7zip\FileManager\Extract.bmp
del /Q 7zip\FileManager\Extract2.bmp
del /Q 7zip\FileManager\ExtractCallback.cpp
del /Q 7zip\FileManager\ExtractCallback.h
del /Q 7zip\FileManager\FileFolderPluginOpen.cpp
del /Q 7zip\FileManager\FileFolderPluginOpen.h
del /Q 7zip\FileManager\FilePlugins.cpp
del /Q 7zip\FileManager\FilePlugins.h
del /Q 7zip\FileManager\FM.cpp
del /Q 7zip\FileManager\FM.dsp
del /Q 7zip\FileManager\FM.dsw
del /Q 7zip\FileManager\FM.ico
del /Q 7zip\FileManager\FormatUtils.cpp
del /Q 7zip\FileManager\FormatUtils.h
del /Q 7zip\FileManager\FSDrives.cpp
del /Q 7zip\FileManager\FSDrives.h
del /Q 7zip\FileManager\FSFolder.cpp
del /Q 7zip\FileManager\FSFolder.h
del /Q 7zip\FileManager\FSFolderCopy.cpp
del /Q 7zip\FileManager\HelpUtils.cpp
del /Q 7zip\FileManager\HelpUtils.h
del /Q 7zip\FileManager\IFolder.h
del /Q 7zip\FileManager\Info.bmp
del /Q 7zip\FileManager\Info2.bmp
del /Q 7zip\FileManager\LangUtils.cpp
del /Q 7zip\FileManager\LangUtils.h
del /Q 7zip\FileManager\Move.bmp
del /Q 7zip\FileManager\Move2.bmp
del /Q 7zip\FileManager\MyLoadMenu.cpp
del /Q 7zip\FileManager\MyLoadMenu.h
del /Q 7zip\FileManager\NetFolder.cpp
del /Q 7zip\FileManager\NetFolder.h
del /Q 7zip\FileManager\OpenCallback.cpp
del /Q 7zip\FileManager\OpenCallback.h
del /Q 7zip\FileManager\OptionsDialog.cpp
del /Q 7zip\FileManager\Panel.cpp
del /Q 7zip\FileManager\Panel.h
del /Q 7zip\FileManager\PanelCopy.cpp
del /Q 7zip\FileManager\PanelFolderChange.cpp
del /Q 7zip\FileManager\PanelItemOpen.cpp
del /Q 7zip\FileManager\PanelItems.cpp
del /Q 7zip\FileManager\PanelKey.cpp
del /Q 7zip\FileManager\PanelListNotify.cpp
del /Q 7zip\FileManager\PanelMenu.cpp
del /Q 7zip\FileManager\PanelOperations.cpp
del /Q 7zip\FileManager\PanelSelect.cpp
del /Q 7zip\FileManager\PanelSort.cpp
del /Q 7zip\FileManager\PluginInterface.h
del /Q 7zip\FileManager\PluginLoader.h
del /Q 7zip\FileManager\ProgramLocation.cpp
del /Q 7zip\FileManager\ProgramLocation.h
del /Q 7zip\FileManager\PropertyName.cpp
del /Q 7zip\FileManager\PropertyName.h
del /Q 7zip\FileManager\RegistryAssociations.cpp
del /Q 7zip\FileManager\RegistryAssociations.h
del /Q 7zip\FileManager\RegistryPlugins.cpp
del /Q 7zip\FileManager\RegistryPlugins.h
del /Q 7zip\FileManager\RegistrySystem.cpp
del /Q 7zip\FileManager\RegistrySystem.h
del /Q 7zip\FileManager\RegistryUtils.cpp
del /Q 7zip\FileManager\RegistryUtils.h
del /Q 7zip\FileManager\resource.h
del /Q 7zip\FileManager\resource.rc
del /Q 7zip\FileManager\RootFolder.cpp
del /Q 7zip\FileManager\RootFolder.h
del /Q 7zip\FileManager\StdAfx.cpp
del /Q 7zip\FileManager\StdAfx.h
del /Q 7zip\FileManager\StringUtils.cpp
del /Q 7zip\FileManager\StringUtils.h
del /Q 7zip\FileManager\SysIconUtils.cpp
del /Q 7zip\FileManager\SysIconUtils.h
del /Q 7zip\FileManager\Test.bmp
del /Q 7zip\FileManager\Test2.bmp
del /Q 7zip\FileManager\TextPairs.cpp
del /Q 7zip\FileManager\TextPairs.h
del /Q 7zip\FileManager\UpdateCallback100.cpp
del /Q 7zip\FileManager\UpdateCallback100.h
del /Q 7zip\FileManager\ViewSettings.cpp
del /Q 7zip\FileManager\ViewSettings.h
del /Q 7zip\FileManager\Resource\AboutDialog\7zipLogo.ico
del /Q 7zip\FileManager\Resource\AboutDialog\AboutDialog.cpp
del /Q 7zip\FileManager\Resource\AboutDialog\AboutDialog.h
del /Q 7zip\FileManager\Resource\AboutDialog\resource.h
del /Q 7zip\FileManager\Resource\AboutDialog\resource.rc
del /Q 7zip\FileManager\Resource\BenchmarkDialog\BenchmarkDialog.cpp
del /Q 7zip\FileManager\Resource\BenchmarkDialog\BenchmarkDialog.h
del /Q 7zip\FileManager\Resource\BenchmarkDialog\resource.h
del /Q 7zip\FileManager\Resource\BenchmarkDialog\resource.rc
del /Q 7zip\FileManager\Resource\ComboDialog\ComboDialog.cpp
del /Q 7zip\FileManager\Resource\ComboDialog\ComboDialog.h
del /Q 7zip\FileManager\Resource\ComboDialog\resource.h
del /Q 7zip\FileManager\Resource\ComboDialog\resource.rc
del /Q 7zip\FileManager\Resource\CopyDialog\CopyDialog.cpp
del /Q 7zip\FileManager\Resource\CopyDialog\CopyDialog.h
del /Q 7zip\FileManager\Resource\CopyDialog\resource.h
del /Q 7zip\FileManager\Resource\CopyDialog\resource.rc
del /Q 7zip\FileManager\Resource\EditPage\EditPage.cpp
del /Q 7zip\FileManager\Resource\EditPage\EditPage.h
del /Q 7zip\FileManager\Resource\EditPage\resource.h
del /Q 7zip\FileManager\Resource\EditPage\resource.rc
del /Q 7zip\FileManager\Resource\LangPage\LangPage.cpp
del /Q 7zip\FileManager\Resource\LangPage\LangPage.h
del /Q 7zip\FileManager\Resource\LangPage\resource.h
del /Q 7zip\FileManager\Resource\LangPage\resource.rc
del /Q 7zip\FileManager\Resource\ListBoxDialog\resource.h
del /Q 7zip\FileManager\Resource\ListBoxDialog\resource.rc
del /Q 7zip\FileManager\Resource\ListViewDialog\ListViewDialog.cpp
del /Q 7zip\FileManager\Resource\ListViewDialog\ListViewDialog.h
del /Q 7zip\FileManager\Resource\ListViewDialog\resource.h
del /Q 7zip\FileManager\Resource\ListViewDialog\resource.rc
del /Q 7zip\FileManager\Resource\MessagesDialog\MessagesDialog.cpp
del /Q 7zip\FileManager\Resource\MessagesDialog\MessagesDialog.h
del /Q 7zip\FileManager\Resource\MessagesDialog\resource.h
del /Q 7zip\FileManager\Resource\MessagesDialog\resource.rc
del /Q 7zip\FileManager\Resource\OverwriteDialog\OverwriteDialog.cpp
del /Q 7zip\FileManager\Resource\OverwriteDialog\OverwriteDialog.h
del /Q 7zip\FileManager\Resource\OverwriteDialog\resource.h
del /Q 7zip\FileManager\Resource\OverwriteDialog\resource.rc
del /Q 7zip\FileManager\Resource\PasswordDialog\PasswordDialog.cpp
del /Q 7zip\FileManager\Resource\PasswordDialog\PasswordDialog.h
del /Q 7zip\FileManager\Resource\PasswordDialog\resource.h
del /Q 7zip\FileManager\Resource\PasswordDialog\resource.rc
del /Q 7zip\FileManager\Resource\PluginsPage\PluginsPage.cpp
del /Q 7zip\FileManager\Resource\PluginsPage\PluginsPage.h
del /Q 7zip\FileManager\Resource\PluginsPage\resource.h
del /Q 7zip\FileManager\Resource\PluginsPage\resource.rc
del /Q 7zip\FileManager\Resource\ProgressDialog\ProgressDialog.cpp
del /Q 7zip\FileManager\Resource\ProgressDialog\ProgressDialog.h
del /Q 7zip\FileManager\Resource\ProgressDialog\resource.h
del /Q 7zip\FileManager\Resource\ProgressDialog\resource.rc
del /Q 7zip\FileManager\Resource\ProgressDialog2\ProgressDialog.cpp
del /Q 7zip\FileManager\Resource\ProgressDialog2\ProgressDialog.h
del /Q 7zip\FileManager\Resource\ProgressDialog2\resource.h
del /Q 7zip\FileManager\Resource\ProgressDialog2\resource.rc
del /Q 7zip\FileManager\Resource\PropertyName\resource.h
del /Q 7zip\FileManager\Resource\PropertyName\resource.rc
del /Q 7zip\FileManager\Resource\SettingsPage\resource.h
del /Q 7zip\FileManager\Resource\SettingsPage\resource.rc
del /Q 7zip\FileManager\Resource\SettingsPage\SettingsPage.cpp
del /Q 7zip\FileManager\Resource\SettingsPage\SettingsPage.h
del /Q 7zip\FileManager\Resource\SystemPage\resource.h
del /Q 7zip\FileManager\Resource\SystemPage\resource.rc
del /Q 7zip\FileManager\Resource\SystemPage\SystemPage.cpp
del /Q 7zip\FileManager\Resource\SystemPage\SystemPage.h
del /Q 7zip\UI\Agent\Agent.cpp
del /Q 7zip\UI\Agent\Agent.h
del /Q 7zip\UI\Agent\AgentOut.cpp
del /Q 7zip\UI\Agent\AgentProxy.cpp
del /Q 7zip\UI\Agent\AgentProxy.h
del /Q 7zip\UI\Agent\ArchiveExtractCallback.cpp
del /Q 7zip\UI\Agent\ArchiveExtractCallback.h
del /Q 7zip\UI\Agent\ArchiveFolder.cpp
del /Q 7zip\UI\Agent\ArchiveFolderOpen.cpp
del /Q 7zip\UI\Agent\ArchiveFolderOut.cpp
del /Q 7zip\UI\Agent\ArchiveUpdateCallback.cpp
del /Q 7zip\UI\Agent\ArchiveUpdateCallback.h
del /Q 7zip\UI\Agent\IFolderArchive.h
del /Q 7zip\UI\Client7z\Client7z.cpp
del /Q 7zip\UI\Client7z\Client7z.dsp
del /Q 7zip\UI\Client7z\Client7z.dsw
del /Q 7zip\UI\Client7z\StdAfx.cpp
del /Q 7zip\UI\Client7z\StdAfx.h
del /Q 7zip\UI\Common\ArchiveName.cpp
del /Q 7zip\UI\Common\ArchiveName.h
del /Q 7zip\UI\Common\ArchiverInfo.cpp
del /Q 7zip\UI\Common\ArchiverInfo.h
del /Q 7zip\UI\Common\CompressCall.cpp
del /Q 7zip\UI\Common\CompressCall.h
del /Q 7zip\UI\Common\DefaultName.cpp
del /Q 7zip\UI\Common\DefaultName.h
del /Q 7zip\UI\Common\DirItem.h
del /Q 7zip\UI\Common\EnumDirItems.cpp
del /Q 7zip\UI\Common\EnumDirItems.h
del /Q 7zip\UI\Common\ExtractingFilePath.cpp
del /Q 7zip\UI\Common\ExtractingFilePath.h
del /Q 7zip\UI\Common\HandlerLoader.h
del /Q 7zip\UI\Common\OpenArchive.cpp
del /Q 7zip\UI\Common\OpenArchive.h
del /Q 7zip\UI\Common\PropIDUtils.cpp
del /Q 7zip\UI\Common\PropIDUtils.h
del /Q 7zip\UI\Common\SortUtils.cpp
del /Q 7zip\UI\Common\SortUtils.h
del /Q 7zip\UI\Common\StdAfx.h
del /Q 7zip\UI\Common\UpdateAction.cpp
del /Q 7zip\UI\Common\UpdateAction.h
del /Q 7zip\UI\Common\UpdatePair.cpp
del /Q 7zip\UI\Common\UpdatePair.h
del /Q 7zip\UI\Common\UpdateProduce.cpp
del /Q 7zip\UI\Common\UpdateProduce.h
del /Q 7zip\UI\Common\WorkDir.cpp
del /Q 7zip\UI\Common\WorkDir.h
del /Q 7zip\UI\Common\ZipRegistry.cpp
del /Q 7zip\UI\Common\ZipRegistry.h
del /Q 7zip\UI\Console\afxres.h
del /Q 7zip\UI\Console\ArError.h
del /Q 7zip\UI\Console\CompressionMode.h
del /Q 7zip\UI\Console\Console.dsp
del /Q 7zip\UI\Console\Console.dsw
del /Q 7zip\UI\Console\ConsoleClose.cpp
del /Q 7zip\UI\Console\ConsoleClose.h
del /Q 7zip\UI\Console\Extract.cpp
del /Q 7zip\UI\Console\Extract.h
del /Q 7zip\UI\Console\ExtractCallback.cpp
del /Q 7zip\UI\Console\ExtractCallback.h
del /Q 7zip\UI\Console\List.cpp
del /Q 7zip\UI\Console\List.h
del /Q 7zip\UI\Console\Main.cpp
del /Q 7zip\UI\Console\MainAr.cpp
del /Q 7zip\UI\Console\OpenCallback.cpp
del /Q 7zip\UI\Console\OpenCallback.h
del /Q 7zip\UI\Console\PercentPrinter.cpp
del /Q 7zip\UI\Console\PercentPrinter.h
del /Q 7zip\UI\Console\resource.h
del /Q 7zip\UI\Console\resource.rc
del /Q 7zip\UI\Console\StdAfx.cpp
del /Q 7zip\UI\Console\StdAfx.h
del /Q 7zip\UI\Console\TempFiles.cpp
del /Q 7zip\UI\Console\TempFiles.h
del /Q 7zip\UI\Console\Update.cpp
del /Q 7zip\UI\Console\Update.h
del /Q 7zip\UI\Console\UpdateCallback.cpp
del /Q 7zip\UI\Console\UpdateCallback.h
del /Q 7zip\UI\Console\UserInputUtils.cpp
del /Q 7zip\UI\Console\UserInputUtils.h
del /Q 7zip\UI\Explorer\7-zip.dll.manifest
del /Q 7zip\UI\Explorer\ContextMenu.cpp
del /Q 7zip\UI\Explorer\ContextMenu.h
del /Q 7zip\UI\Explorer\ContextMenuFlags.h
del /Q 7zip\UI\Explorer\DllExports.cpp
del /Q 7zip\UI\Explorer\Explorer.def
del /Q 7zip\UI\Explorer\Explorer.dsp
del /Q 7zip\UI\Explorer\Explorer.dsw
del /Q 7zip\UI\Explorer\MyMessages.cpp
del /Q 7zip\UI\Explorer\MyMessages.h
del /Q 7zip\UI\Explorer\OptionsDialog.cpp
del /Q 7zip\UI\Explorer\OptionsDialog.h
del /Q 7zip\UI\Explorer\RegistryContextMenu..cpp
del /Q 7zip\UI\Explorer\RegistryContextMenu.h
del /Q 7zip\UI\Explorer\resource.h
del /Q 7zip\UI\Explorer\resource.rc
del /Q 7zip\UI\Explorer\StdAfx.cpp
del /Q 7zip\UI\Explorer\StdAfx.h
del /Q 7zip\UI\Explorer\FoldersPage\FoldersPage.cpp
del /Q 7zip\UI\Explorer\FoldersPage\FoldersPage.h
del /Q 7zip\UI\Explorer\FoldersPage\resource.h
del /Q 7zip\UI\Explorer\FoldersPage\resource.rc
del /Q 7zip\UI\Explorer\SystemPage\resource.h
del /Q 7zip\UI\Explorer\SystemPage\resource.rc
del /Q 7zip\UI\Explorer\SystemPage\SystemPage.cpp
del /Q 7zip\UI\Explorer\SystemPage\SystemPage.h
del /Q 7zip\UI\Far\CLSIDConst.cpp
del /Q 7zip\UI\Far\CompressEngine.cpp
del /Q 7zip\UI\Far\CompressEngine.h
del /Q 7zip\UI\Far\ExtractEngine.cpp
del /Q 7zip\UI\Far\ExtractEngine.h
del /Q 7zip\UI\Far\Far.def
del /Q 7zip\UI\Far\Far.dsp
del /Q 7zip\UI\Far\Far.dsw
del /Q 7zip\UI\Far\Far.rc
del /Q 7zip\UI\Far\Main.cpp
del /Q 7zip\UI\Far\Messages.h
del /Q 7zip\UI\Far\OverwriteDialog.cpp
del /Q 7zip\UI\Far\OverwriteDialog.h
del /Q 7zip\UI\Far\Plugin.cpp
del /Q 7zip\UI\Far\Plugin.h
del /Q 7zip\UI\Far\PluginCommon.cpp
del /Q 7zip\UI\Far\PluginDelete.cpp
del /Q 7zip\UI\Far\PluginRead.cpp
del /Q 7zip\UI\Far\PluginWrite.cpp
del /Q 7zip\UI\Far\resource.h
del /Q 7zip\UI\Far\StdAfx.cpp
del /Q 7zip\UI\Far\StdAfx.h
del /Q 7zip\UI\Far\UpdateCallback100.cpp
del /Q 7zip\UI\Far\UpdateCallback100.h
del /Q 7zip\UI\GUI\7zG.exe.manifest
del /Q 7zip\UI\GUI\Compress.cpp
del /Q 7zip\UI\GUI\Compress.h
del /Q 7zip\UI\GUI\CompressDialog.cpp
del /Q 7zip\UI\GUI\CompressDialog.h
del /Q 7zip\UI\GUI\Extract.cpp
del /Q 7zip\UI\GUI\Extract.h
del /Q 7zip\UI\GUI\ExtractDialog.cpp
del /Q 7zip\UI\GUI\ExtractDialog.h
del /Q 7zip\UI\GUI\FM.ico
del /Q 7zip\UI\GUI\GUI.cpp
del /Q 7zip\UI\GUI\GUI.dsp
del /Q 7zip\UI\GUI\GUI.dsw
del /Q 7zip\UI\GUI\resource.h
del /Q 7zip\UI\GUI\resource.rc
del /Q 7zip\UI\GUI\StdAfx.cpp
del /Q 7zip\UI\GUI\StdAfx.h
del /Q 7zip\UI\GUI\Test.cpp
del /Q 7zip\UI\GUI\Test.h
del /Q 7zip\UI\Resource\CompressDialog\resource.h
del /Q 7zip\UI\Resource\CompressDialog\resource.rc
del /Q 7zip\UI\Resource\Extract\resource.h
del /Q 7zip\UI\Resource\Extract\resource.rc
del /Q 7zip\UI\Resource\ExtractDialog\resource.h
del /Q 7zip\UI\Resource\ExtractDialog\resource.rc
del /Q Common\CommandLineParser.cpp
del /Q Common\CommandLineParser.h
del /Q Common\Lang.cpp
del /Q Common\Lang.h
del /Q Common\ListFileUtils.cpp
del /Q Common\ListFileUtils.h
del /Q Common\NewHandler.cpp
del /Q Common\Random.cpp
del /Q Common\Random.h
del /Q Common\StdAfx.h
del /Q Common\StdInStream.cpp
del /Q Common\StdInStream.h
del /Q Common\StdOutStream.cpp
del /Q Common\StdOutStream.h
del /Q Common\TextConfig.cpp
del /Q Common\TextConfig.h
del /Q Common\UTFConvert.cpp
del /Q Common\UTFConvert.h
del /Q Common\WindowsTypes.h
del /Q Far\FarPlugin.h
del /Q Far\FarUtils.cpp
del /Q Far\FarUtils.h
del /Q Far\ProgressBox.cpp
del /Q Far\ProgressBox.h
del /Q Windows\COM.cpp
del /Q Windows\COM.h
del /Q Windows\Console.cpp
del /Q Windows\Console.h
del /Q Windows\Error.cpp
del /Q Windows\Error.h
del /Q Windows\FileMapping.cpp
del /Q Windows\FileMapping.h
del /Q Windows\FileName.cpp
del /Q Windows\FileSystem.cpp
del /Q Windows\FileSystem.h
del /Q Windows\ItemIDListUtils.cpp
del /Q Windows\ItemIDListUtils.h
del /Q Windows\Memory.cpp
del /Q Windows\Memory.h
del /Q Windows\Menu.h
del /Q Windows\Net.cpp
del /Q Windows\Net.h
del /Q Windows\ProcessMessages.cpp
del /Q Windows\ProcessMessages.h
del /Q Windows\Registry.cpp
del /Q Windows\Registry.h
del /Q Windows\ResourceString.cpp
del /Q Windows\ResourceString.h
del /Q Windows\Shell.cpp
del /Q Windows\Shell.h
del /Q Windows\StdAfx.h
del /Q Windows\Time.h
del /Q Windows\Window.cpp
del /Q Windows\Window.h
del /Q Windows\Control\ComboBox.cpp
del /Q Windows\Control\ComboBox.h
del /Q Windows\Control\Dialog.cpp
del /Q Windows\Control\Dialog.h
del /Q Windows\Control\Edit.h
del /Q Windows\Control\ImageList.cpp
del /Q Windows\Control\ImageList.h
del /Q Windows\Control\ListView.cpp
del /Q Windows\Control\ListView.h
del /Q Windows\Control\ProgressBar.h
del /Q Windows\Control\PropertyPage.cpp
del /Q Windows\Control\PropertyPage.h
del /Q Windows\Control\ReBar.h
del /Q Windows\Control\Static.h
del /Q Windows\Control\StatusBar.h
del /Q Windows\Control\ToolBar.h
del /Q Windows\Control\Trackbar.h
del /Q Windows\Control\Window2.cpp
del /Q Windows\Control\Window2.h

rem smazat prazdne adresare

rmdir /Q Far

rmdir /Q 7zip\Bundles\Alone
rmdir /Q 7zip\Bundles\Format7z
rmdir /Q 7zip\Bundles\SFXCon
rmdir /Q 7zip\Bundles\SFXSetup
rmdir /Q 7zip\Bundles\SFXWin
rmdir /Q 7zip\Bundles

rmdir /Q 7zip\Archive\Arj
rmdir /Q 7zip\Archive\BZip2
rmdir /Q 7zip\Archive\Cab
rmdir /Q 7zip\Archive\cpio
rmdir /Q 7zip\Archive\Deb
rmdir /Q 7zip\Archive\GZip
rmdir /Q 7zip\Archive\Rar
rmdir /Q 7zip\Archive\RPM
rmdir /Q 7zip\Archive\Split
rmdir /Q 7zip\Archive\Tar
rmdir /Q 7zip\Archive\Zip

rmdir /Q 7zip\UI\Agent
rmdir /Q 7zip\UI\Client7z
rmdir /Q 7zip\UI\Common
rmdir /Q 7zip\UI\Console
rmdir /Q 7zip\UI\Explorer\SystemPage
rmdir /Q 7zip\UI\Explorer\FoldersPage
rmdir /Q 7zip\UI\Explorer

rmdir /Q 7zip\UI\Far
rmdir /Q 7zip\UI\GUI
rmdir /Q 7zip\UI\Resource\CompressDialog
rmdir /Q 7zip\UI\Resource\Extract
rmdir /Q 7zip\UI\Resource\ExtractDialog
rmdir /Q 7zip\UI\Resource
rmdir /Q 7zip\UI

rmdir /Q 7zip\Crypto\Rar20
rmdir /Q 7zip\Crypto\RarAES
rmdir /Q 7zip\Crypto\Zip

rmdir /Q 7zip\Compress\Arj
rmdir /Q 7zip\Compress\ByteSwap
rmdir /Q 7zip\Compress\BZip2
rmdir /Q 7zip\Compress\Deflate
rmdir /Q 7zip\Compress\Huffman
rmdir /Q 7zip\Compress\Implode

rmdir /Q Windows\Control

rmdir /Q 7zip\FileManager\Resource\AboutDialog
rmdir /Q 7zip\FileManager\Resource\BenchmarkDialog
rmdir /Q 7zip\FileManager\Resource\ComboDialog
rmdir /Q 7zip\FileManager\Resource\CopyDialog
rmdir /Q 7zip\FileManager\Resource\EditPage
rmdir /Q 7zip\FileManager\Resource\LangPage
rmdir /Q 7zip\FileManager\Resource\ListBoxDialog
rmdir /Q 7zip\FileManager\Resource\ListViewDialog
rmdir /Q 7zip\FileManager\Resource\MessagesDialog
rmdir /Q 7zip\FileManager\Resource\OverwriteDialog
rmdir /Q 7zip\FileManager\Resource\PasswordDialog
rmdir /Q 7zip\FileManager\Resource\PluginsPage
rmdir /Q 7zip\FileManager\Resource\ProgressDialog
rmdir /Q 7zip\FileManager\Resource\ProgressDialog2
rmdir /Q 7zip\FileManager\Resource\PropertyName
rmdir /Q 7zip\FileManager\Resource\SettingsPage
rmdir /Q 7zip\FileManager\Resource\SystemPage
rmdir /Q 7zip\FileManager\Resource
rmdir /Q 7zip\FileManager

