del winscp.spl
del lang\english.slg
del Salamand.drc
del Salamand.lib
del Salamand.map
del Salamand.tds
del *.mak
del "packages\my\*.dcu"
del "packages\my\*.hpp"
del packages\*.mak
del lib\*.lib
del lib\*.bpi
del lib\*.bpl
del lib\*.tds
del core\*.obj
del forms\*.obj
del windows\*.obj
del packages\*.obj
del "packages\my\*.obj"
del putty\*.obj
del putty\charset\*.obj
del putty\windows\*.obj
del salamander\*.obj
del salamander\Salamander.res
del salamander\SalamanderShared.res
del ..\shared\*.obj
del lang\english.tds
del "packages\theme\*.dcu"
del "packages\theme\*.hpp"
del "packages\theme\*.obj"
del *.res
del salamand.lang.obj
del Salamand_DRC.rc
del makefile.lang
del Salamand.lang.cpp
del Salamand.lang.rc
rmdir /S /Q translations\lang

del lang\*.slg
