// Defines for Altap Translator
#define IDOK                1
#define IDCANCEL            2
#define IDABORT             3
#define IDRETRY             4
#define IDIGNORE            5
#define IDYES               6
#define IDNO                7
#define IDCLOSE             8
#define IDHELP              9

///* X:\ALTAP\PETR\salamand\plugins\unchm\lang\lang.rh
//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by lang.rc
//

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        8500
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         8700
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
///* X:\ALTAP\PETR\salamand\plugins\unchm\unchm.rh2
#pragma once

#if defined(APSTUDIO_INVOKED) && !defined(APSTUDIO_READONLY_SYMBOLS)
#error this file is not editable by Microsoft Visual C++
#endif //defined(APSTUDIO_INVOKED) && !defined(APSTUDIO_READONLY_SYMBOLS)

//***********************************************************************************
//
// texty
//

#define IDS_PLUGINNAME              1000
#define IDS_CANT_OPEN               1001

#define IDS_UNKNOW_ERROR            1002
#define IDS_UNPACKING_ARCHIVE       1003
#define IDS_ERROR_UNPACKING         1004
#define IDS_CANT_HANDLE_FILE        1005
#define IDS_INSUFFICIENT_MEMORY     1006

#define IDS_ABOUT                   1007
#define IDS_PLUGIN_DESCRIPTION      1009
#define IDS_CANT_CREATE_TEMP        1010
#define IDS_CANT_DELETE_TEMP_FILE   1011
#define IDS_UNKNOWN_FILE_FORMAT     1012
#define IDS_CANT_OPEN_FILE          1013
#define IDS_ERR_TMP                 1014
#define IDS_CANT_SET_ATTRS          1015
#define IDS_CANT_CREATE_DIR         1016
#define IDS_YES                     1020
#define IDS_NO                      1021
#define IDS_ERROR                   1022
#define IDS_WARNING                 1023
#define IDS_INTERNAL_PLUGIN_ERROR   1032

#define IDS_READERROR               1100
#define IDS_WRITEERROR              1101

#define IDS_INVALIDNUMBER           1105
#define IDS_CANCELOPER              1106

#define IDS_CHMLIBCOPYRIGHT         1107
